;;; this file is automatically generated, do not edit
#||
"Copyright (c) 2015-2017 The Khronos Group Inc.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and/or associated documentation files (the
\"Materials\"), to deal in the Materials without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Materials, and to
permit persons to whom the Materials are furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Materials.

THE MATERIALS ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.

------------------------------------------------------------------------"
||#

;; Changes (into Lisp) Copyright 2019, 2020 Andrew Kenneth Wolven
;; <awolven@gmail.com>
;; 
;; Permission is hereby granted, free of charge, to any person obtaining
;; a copy of this software and associated documentation files (the
;; "Software"), to deal in the Software without restriction, including
;; without limitation the rights to use, copy, modify, merge, publish,
;; distribute, sublicense, and/or sell copies of the Software, and to
;; permit persons to whom the Software is furnished to do so, subject to
;; the following conditions:
;; 
;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.
;; 
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
;; LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
;; OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
;; WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(cl:in-package #:%vk)

(cl:defconstant VK_TRUE 1)
(cl:defconstant VK_FALSE 0)

(cl:defparameter *known-extension-names*
  '("VK_KHR_surface"
    "VK_KHR_swapchain"
    "VK_KHR_display"
    "VK_KHR_display_swapchain"
    "VK_KHR_xlib_surface"
    "VK_KHR_xcb_surface"
    "VK_KHR_wayland_surface"
    "VK_KHR_mir_surface"
    "VK_KHR_android_surface"
    "VK_KHR_win32_surface"
    "VK_EXT_debug_report"
    "VK_NV_glsl_shader"
    "VK_NV_extension_1"
    "VK_KHR_sampler_mirror_clamp_to_edge"
    "VK_IMG_filter_cubic"
    "VK_AMD_extension_17"
    "VK_AMD_extension_18"
    "VK_AMD_rasterization_order"
    "VK_AMD_extension_20"
    "VK_AMD_shader_trinary_minmax"
    "VK_AMD_shader_explicit_vertex_parameter"
    "VK_EXT_debug_marker"
    "VK_AMD_extension_24"
    "VK_AMD_extension_25"
    "VK_AMD_gcn_shader"
    "VK_NV_dedicated_allocation"
    "VK_NV_extension_28"
    "VK_NVX_extension_29"
    "VK_NVX_extension_30"
    "VK_NVX_extension_31"
    "VK_AMD_extension_32"
    "VK_AMD_extension_33"
    "VK_AMD_draw_indirect_count"
    "VK_AMD_extension_35"
    "VK_AMD_negative_viewport_height"
    "VK_AMD_gpu_shader_half_float"
    "VK_AMD_shader_ballot"
    "VK_AMD_extension_39"
    "VK_AMD_extension_40"
    "VK_AMD_extension_41"
    "VK_AMD_texture_gather_bias_lod"
    "VK_AMD_extension_43"
    "VK_AMD_extension_44"
    "VK_AMD_extension_45"
    "VK_AMD_extension_46"
    "VK_AMD_extension_47"
    "VK_NVX_extension_48"
    "VK_GOOGLE_extension_49"
    "VK_GOOGLE_extension_50"
    "VK_NVX_extension_51"
    "VK_NVX_extension_52"
    "VK_NV_extension_53"
    "VK_KHX_multiview"
    "VK_IMG_format_pvrtc"
    "VK_NV_external_memory_capabilities"
    "VK_NV_external_memory"
    "VK_NV_external_memory_win32"
    "VK_NV_win32_keyed_mutex"
    "VK_KHR_get_physical_device_properties2"
    "VK_KHX_device_group"
    "VK_EXT_validation_flags"
    "VK_NN_vi_surface"
    "VK_KHR_shader_draw_parameters"
    "VK_EXT_shader_subgroup_ballot"
    "VK_EXT_shader_subgroup_vote"
    "VK_ARM_extension_01"
    "VK_ARM_extension_02"
    "VK_IMG_extension_69"
    "VK_KHR_maintenance1"
    "VK_KHX_device_group_creation"
    "VK_KHX_external_memory_capabilities"
    "VK_KHX_external_memory"
    "VK_KHX_external_memory_win32"
    "VK_KHX_external_memory_fd"
    "VK_KHX_win32_keyed_mutex"
    "VK_KHX_external_semaphore_capabilities"
    "VK_KHX_external_semaphore"
    "VK_KHX_external_semaphore_win32"
    "VK_KHX_external_semaphore_fd"
    "VK_KHR_push_descriptor"
    "VK_KHR_extension_82"
    "VK_KHR_extension_83"
    "VK_KHR_extension_84"
    "VK_KHR_incremental_present"
    "VK_KHR_descriptor_update_template"
    "VK_NVX_device_generated_commands"
    "VK_NV_clip_space_w_scaling"
    "VK_EXT_direct_mode_display"
    "VK_EXT_acquire_xlib_display"
    "VK_EXT_display_surface_counter"
    "VK_EXT_display_control"
    "VK_GOOGLE_display_timing"
    "VK_KHR_extension_94"
    "VK_NV_sample_mask_override_coverage"
    "VK_NV_geometry_shader_passthrough"
    "VK_NV_viewport_array2"
    "VK_NVX_multiview_per_view_attributes"
    "VK_NV_viewport_swizzle"
    "VK_EXT_discard_rectangles"
    "VK_NV_extension_101"
    "VK_NV_extension_102"
    "VK_NV_extension_103"
    "VK_NV_extension_104"
    "VK_EXT_swapchain_colorspace"
    "VK_EXT_hdr_metadata"
    "VK_IMG_extension_107"
    "VK_IMG_extension_108"
    "VK_IMG_extension_109"
    "VK_IMG_extension_110"
    "VK_IMG_extension_111"
    "VK_KHR_shared_presentable_image"
    "VK_KHR_extension_113"
    "VK_KHR_extension_114"
    "VK_KHR_extension_115"
    "VK_KHR_extension_116"
    "VK_KHR_extension_117"
    "VK_KHR_extension_118"
    "VK_KHR_extension_119"
    "VK_KHR_get_surface_capabilities2"
    "VK_KHR_variable_pointers"
    "VK_KHR_extension_122"
    "VK_MVK_ios_surface"
    "VK_MVK_macos_surface"
    "VK_MVK_moltenvk"
    "VK_MESA_extension_126"
    "VK_MESA_extension_127"
    "VK_KHR_extension_128"
    "VK_EXT_extension_129"
    "VK_KHR_extension_130"
    "VK_KHR_extension_131"
    "VK_KHR_extension_132"
    "VK_AMD_extension_133"
    "VK_AMD_extension_134"
    "VK_AMD_extension_135"
    "VK_AMD_extension_136"
    "VK_AMD_extension_137"
    "VK_AMD_extension_138"
    "VK_AMD_extension_139"
    "VK_AMD_extension_140"
    "VK_AMD_extension_141"
    "VK_AMD_extension_142"
    "VK_AMD_extension_143"
    "VK_AMD_extension_144"
    "VK_KHR_relaxed_block_layout"
    "VK_KHR_extension_146"
    "VK_KHR_extension_147"
    "VK_EXT_extension_148"
    "VK_NV_extension_149"
    "VK_NV_extension_150"
    "VK_NV_extension_151"
    "VK_NV_extension_152"
    "VK_NV_extension_153"
    "VK_NV_extension_154"
    "VK_NV_extension_155"
    "VK_NV_extension_156"
    "VK_KHR_extension_157"
    "VK_KHR_extension_158"
    "VK_EXT_extension_159"))

;;types
(cffi:defctype VkSampleMask :uint32)
(cffi:defctype VkBool32 :uint32)
(cffi:defctype VkFlags :uint32)
(cffi:defctype VkDeviceSize :uint64)
(cffi:defctype handle :pointer)
(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:if (cl:= 8 (cffi:foreign-type-size :pointer))
	 (cl:progn
	   (cffi:defctype size-t :uint64)
	   (cffi:defctype non-dispatch-handle :pointer))
	 (cl:progn
	   (cffi:defctype size-t :uint32)
	   (cffi:defctype non-dispatch-handle :uint64))))
(cffi:defctype ANativeWindow :void)
(cffi:defctype MirConnection :void)
(cffi:defctype MirSurface :void)
(cffi:defctype xcb_connection_t :void)
(cffi:defctype Display :void)
(cffi:defctype HINSTANCE (:pointer :void))
(cffi:defctype HWND (:pointer :void))
(cffi:defctype HANDLE (:pointer :void))
(cffi:defctype DWORD :uint32)
(cffi:defctype LPCWSTR (:pointer :void))
(cffi:defctype RROutput :ulong)
(cffi:defctype xcb_window_t :uint32)
(cffi:defctype window :ulong)
(cffi:defctype VisualID :ulong)
(cffi:defctype SECURITY_ATTRIBUTES (:pointer :void))
(cffi:defctype VkInstance HANDLE)
(cffi:defctype VkPhysicalDevice HANDLE)
(cffi:defctype VkDevice HANDLE)
(cffi:defctype VkQueue HANDLE)
(cffi:defctype VkCommandBuffer HANDLE)
(cffi:defctype VkDeviceMemory NON-DISPATCH-HANDLE)
(cffi:defctype VkCommandPool NON-DISPATCH-HANDLE)
(cffi:defctype VkBuffer NON-DISPATCH-HANDLE)
(cffi:defctype VkBufferView NON-DISPATCH-HANDLE)
(cffi:defctype VkImage NON-DISPATCH-HANDLE)
(cffi:defctype VkImageView NON-DISPATCH-HANDLE)
(cffi:defctype VkShaderModule NON-DISPATCH-HANDLE)
(cffi:defctype VkPipeline NON-DISPATCH-HANDLE)
(cffi:defctype VkPipelineLayout NON-DISPATCH-HANDLE)
(cffi:defctype VkSampler NON-DISPATCH-HANDLE)
(cffi:defctype VkDescriptorSet NON-DISPATCH-HANDLE)
(cffi:defctype VkDescriptorSetLayout NON-DISPATCH-HANDLE)
(cffi:defctype VkDescriptorPool NON-DISPATCH-HANDLE)
(cffi:defctype VkFence NON-DISPATCH-HANDLE)
(cffi:defctype VkSemaphore NON-DISPATCH-HANDLE)
(cffi:defctype VkEvent NON-DISPATCH-HANDLE)
(cffi:defctype VkQueryPool NON-DISPATCH-HANDLE)
(cffi:defctype VkFramebuffer NON-DISPATCH-HANDLE)
(cffi:defctype VkRenderPass NON-DISPATCH-HANDLE)
(cffi:defctype VkPipelineCache NON-DISPATCH-HANDLE)
(cffi:defctype VkObjectTableNVX NON-DISPATCH-HANDLE)
(cffi:defctype VkIndirectCommandsLayoutNVX NON-DISPATCH-HANDLE)
(cffi:defctype VkDescriptorUpdateTemplateKHR NON-DISPATCH-HANDLE)
(cffi:defctype VkDisplayKHR NON-DISPATCH-HANDLE)
(cffi:defctype VkDisplayModeKHR NON-DISPATCH-HANDLE)
(cffi:defctype VkSurfaceKHR NON-DISPATCH-HANDLE)
(cffi:defctype VkSwapchainKHR NON-DISPATCH-HANDLE)
(cffi:defctype VkDebugReportCallbackEXT NON-DISPATCH-HANDLE)

(cffi:defctype VkAccessFlagBits VkFlags)
(cffi:defctype VkAccessFlags VkFlags)
(cffi:defctype VkAndroidSurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkAttachmentDescriptionFlagBits VkFlags)
(cffi:defctype VkAttachmentDescriptionFlags VkFlags)
(cffi:defctype VkBufferCreateFlagBits VkFlags)
(cffi:defctype VkBufferCreateFlags VkFlags)
(cffi:defctype VkBufferUsageFlagBits VkFlags)
(cffi:defctype VkBufferUsageFlags VkFlags)
(cffi:defctype VkBufferViewCreateFlags VkFlags)
(cffi:defctype VkColorComponentFlagBits VkFlags)
(cffi:defctype VkColorComponentFlags VkFlags)
(cffi:defctype VkCommandBufferResetFlagBits VkFlags)
(cffi:defctype VkCommandBufferResetFlags VkFlags)
(cffi:defctype VkCommandBufferUsageFlagBits VkFlags)
(cffi:defctype VkCommandBufferUsageFlags VkFlags)
(cffi:defctype VkCommandPoolCreateFlagBits VkFlags)
(cffi:defctype VkCommandPoolCreateFlags VkFlags)
(cffi:defctype VkCommandPoolResetFlagBits VkFlags)
(cffi:defctype VkCommandPoolResetFlags VkFlags)
(cffi:defctype VkCommandPoolTrimFlagsKHR VkFlags)
(cffi:defctype VkCompositeAlphaFlagBitsKHR VkFlags)
(cffi:defctype VkCompositeAlphaFlagsKHR VkFlags)
(cffi:defctype VkCullModeFlagBits VkFlags)
(cffi:defctype VkCullModeFlags VkFlags)
(cffi:defctype VkDebugReportFlagBitsEXT VkFlags)
(cffi:defctype VkDebugReportFlagsEXT VkFlags)
(cffi:defctype VkDependencyFlagBits VkFlags)
(cffi:defctype VkDependencyFlags VkFlags)
(cffi:defctype VkDescriptorPoolCreateFlagBits VkFlags)
(cffi:defctype VkDescriptorPoolCreateFlags VkFlags)
(cffi:defctype VkDescriptorPoolResetFlags VkFlags)
(cffi:defctype VkDescriptorSetLayoutCreateFlagBits VkFlags)
(cffi:defctype VkDescriptorSetLayoutCreateFlags VkFlags)
(cffi:defctype VkDescriptorUpdateTemplateCreateFlagsKHR VkFlags)
(cffi:defctype VkDeviceCreateFlags VkFlags)
(cffi:defctype VkDeviceGroupPresentModeFlagBitsKHX VkFlags)
(cffi:defctype VkDeviceGroupPresentModeFlagsKHX VkFlags)
(cffi:defctype VkDeviceQueueCreateFlags VkFlags)
(cffi:defctype VkDisplayModeCreateFlagsKHR VkFlags)
(cffi:defctype VkDisplayPlaneAlphaFlagBitsKHR VkFlags)
(cffi:defctype VkDisplayPlaneAlphaFlagsKHR VkFlags)
(cffi:defctype VkDisplaySurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkEventCreateFlags VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagBitsNV VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagsKHX VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagsNV VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagBitsKHX VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagBitsNV VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagsKHX VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagsNV VkFlags)
(cffi:defctype VkExternalSemaphoreFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkExternalSemaphoreFeatureFlagsKHX VkFlags)
(cffi:defctype VkExternalSemaphoreHandleTypeFlagBitsKHX VkFlags)
(cffi:defctype VkExternalSemaphoreHandleTypeFlagsKHX VkFlags)
(cffi:defctype VkFenceCreateFlagBits VkFlags)
(cffi:defctype VkFenceCreateFlags VkFlags)
(cffi:defctype VkFormatFeatureFlagBits VkFlags)
(cffi:defctype VkFormatFeatureFlags VkFlags)
(cffi:defctype VkFramebufferCreateFlags VkFlags)
(cffi:defctype VkIOSSurfaceCreateFlagsMVK VkFlags)
(cffi:defctype VkImageAspectFlagBits VkFlags)
(cffi:defctype VkImageAspectFlags VkFlags)
(cffi:defctype VkImageCreateFlagBits VkFlags)
(cffi:defctype VkImageCreateFlags VkFlags)
(cffi:defctype VkImageUsageFlagBits VkFlags)
(cffi:defctype VkImageUsageFlags VkFlags)
(cffi:defctype VkImageViewCreateFlags VkFlags)
(cffi:defctype VkIndirectCommandsLayoutUsageFlagBitsNVX VkFlags)
(cffi:defctype VkIndirectCommandsLayoutUsageFlagsNVX VkFlags)
(cffi:defctype VkInstanceCreateFlags VkFlags)
(cffi:defctype VkMacOSSurfaceCreateFlagsMVK VkFlags)
(cffi:defctype VkMemoryAllocateFlagBitsKHX VkFlags)
(cffi:defctype VkMemoryAllocateFlagsKHX VkFlags)
(cffi:defctype VkMemoryHeapFlagBits VkFlags)
(cffi:defctype VkMemoryHeapFlags VkFlags)
(cffi:defctype VkMemoryMapFlags VkFlags)
(cffi:defctype VkMemoryPropertyFlagBits VkFlags)
(cffi:defctype VkMemoryPropertyFlags VkFlags)
(cffi:defctype VkMirSurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkObjectEntryUsageFlagBitsNVX VkFlags)
(cffi:defctype VkObjectEntryUsageFlagsNVX VkFlags)
(cffi:defctype VkPeerMemoryFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkPeerMemoryFeatureFlagsKHX VkFlags)
(cffi:defctype VkPipelineCacheCreateFlags VkFlags)
(cffi:defctype VkPipelineColorBlendStateCreateFlags VkFlags)
(cffi:defctype VkPipelineCreateFlagBits VkFlags)
(cffi:defctype VkPipelineCreateFlags VkFlags)
(cffi:defctype VkPipelineDepthStencilStateCreateFlags VkFlags)
(cffi:defctype VkPipelineDiscardRectangleStateCreateFlagsEXT VkFlags)
(cffi:defctype VkPipelineDynamicStateCreateFlags VkFlags)
(cffi:defctype VkPipelineInputAssemblyStateCreateFlags VkFlags)
(cffi:defctype VkPipelineLayoutCreateFlags VkFlags)
(cffi:defctype VkPipelineMultisampleStateCreateFlags VkFlags)
(cffi:defctype VkPipelineRasterizationStateCreateFlags VkFlags)
(cffi:defctype VkPipelineShaderStageCreateFlags VkFlags)
(cffi:defctype VkPipelineStageFlagBits VkFlags)
(cffi:defctype VkPipelineStageFlags VkFlags)
(cffi:defctype VkPipelineTessellationStateCreateFlags VkFlags)
(cffi:defctype VkPipelineVertexInputStateCreateFlags VkFlags)
(cffi:defctype VkPipelineViewportStateCreateFlags VkFlags)
(cffi:defctype VkPipelineViewportSwizzleStateCreateFlagsNV VkFlags)
(cffi:defctype VkQueryControlFlagBits VkFlags)
(cffi:defctype VkQueryControlFlags VkFlags)
(cffi:defctype VkQueryPipelineStatisticFlagBits VkFlags)
(cffi:defctype VkQueryPipelineStatisticFlags VkFlags)
(cffi:defctype VkQueryPoolCreateFlags VkFlags)
(cffi:defctype VkQueryResultFlagBits VkFlags)
(cffi:defctype VkQueryResultFlags VkFlags)
(cffi:defctype VkQueueFlagBits VkFlags)
(cffi:defctype VkQueueFlags VkFlags)
(cffi:defctype VkRenderPassCreateFlags VkFlags)
(cffi:defctype VkSampleCountFlagBits VkFlags)
(cffi:defctype VkSampleCountFlags VkFlags)
(cffi:defctype VkSamplerCreateFlags VkFlags)
(cffi:defctype VkSemaphoreCreateFlags VkFlags)
(cffi:defctype VkShaderModuleCreateFlags VkFlags)
(cffi:defctype VkShaderStageFlagBits VkFlags)
(cffi:defctype VkShaderStageFlags VkFlags)
(cffi:defctype VkSparseImageFormatFlagBits VkFlags)
(cffi:defctype VkSparseImageFormatFlags VkFlags)
(cffi:defctype VkSparseMemoryBindFlagBits VkFlags)
(cffi:defctype VkSparseMemoryBindFlags VkFlags)
(cffi:defctype VkStencilFaceFlagBits VkFlags)
(cffi:defctype VkStencilFaceFlags VkFlags)
(cffi:defctype VkSubpassDescriptionFlagBits VkFlags)
(cffi:defctype VkSubpassDescriptionFlags VkFlags)
(cffi:defctype VkSurfaceCounterFlagBitsEXT VkFlags)
(cffi:defctype VkSurfaceCounterFlagsEXT VkFlags)
(cffi:defctype VkSurfaceTransformFlagBitsKHR VkFlags)
(cffi:defctype VkSurfaceTransformFlagsKHR VkFlags)
(cffi:defctype VkSwapchainCreateFlagBitsKHR VkFlags)
(cffi:defctype VkSwapchainCreateFlagsKHR VkFlags)
(cffi:defctype VkViSurfaceCreateFlagsNN VkFlags)
(cffi:defctype VkWaylandSurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkWin32SurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkXcbSurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkXlibSurfaceCreateFlagsKHR VkFlags)
(cffi:defctype VkAccessFlagBits VkFlags)
(cffi:defctype VkAttachmentDescriptionFlagBits VkFlags)
(cffi:defctype VkAttachmentLoadOp VkFlags)
(cffi:defctype VkAttachmentStoreOp VkFlags)
(cffi:defctype VkBlendFactor VkFlags)
(cffi:defctype VkBlendOp VkFlags)
(cffi:defctype VkBorderColor VkFlags)
(cffi:defctype VkBufferCreateFlagBits VkFlags)
(cffi:defctype VkBufferUsageFlagBits VkFlags)
(cffi:defctype VkColorComponentFlagBits VkFlags)
(cffi:defctype VkColorSpaceKHR VkFlags)
(cffi:defctype VkCommandBufferLevel VkFlags)
(cffi:defctype VkCommandBufferResetFlagBits VkFlags)
(cffi:defctype VkCommandBufferUsageFlagBits VkFlags)
(cffi:defctype VkCommandPoolCreateFlagBits VkFlags)
(cffi:defctype VkCommandPoolResetFlagBits VkFlags)
(cffi:defctype VkCompareOp VkFlags)
(cffi:defctype VkComponentSwizzle VkFlags)
(cffi:defctype VkCompositeAlphaFlagBitsKHR VkFlags)
(cffi:defctype VkCullModeFlagBits VkFlags)
(cffi:defctype VkDebugReportFlagBitsEXT VkFlags)
(cffi:defctype VkDebugReportObjectTypeEXT VkFlags)
(cffi:defctype VkDependencyFlagBits VkFlags)
(cffi:defctype VkDescriptorPoolCreateFlagBits VkFlags)
(cffi:defctype VkDescriptorSetLayoutCreateFlagBits VkFlags)
(cffi:defctype VkDescriptorType VkFlags)
(cffi:defctype VkDescriptorUpdateTemplateTypeKHR VkFlags)
(cffi:defctype VkDeviceEventTypeEXT VkFlags)
(cffi:defctype VkDeviceGroupPresentModeFlagBitsKHX VkFlags)
(cffi:defctype VkDiscardRectangleModeEXT VkFlags)
(cffi:defctype VkDisplayEventTypeEXT VkFlags)
(cffi:defctype VkDisplayPlaneAlphaFlagBitsKHR VkFlags)
(cffi:defctype VkDisplayPowerStateEXT VkFlags)
(cffi:defctype VkDynamicState VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkExternalMemoryFeatureFlagBitsNV VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagBitsKHX VkFlags)
(cffi:defctype VkExternalMemoryHandleTypeFlagBitsNV VkFlags)
(cffi:defctype VkExternalSemaphoreFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkExternalSemaphoreHandleTypeFlagBitsKHX VkFlags)
(cffi:defctype VkFenceCreateFlagBits VkFlags)
(cffi:defctype VkFilter VkFlags)
(cffi:defctype VkFormat VkFlags)
(cffi:defctype VkFormatFeatureFlagBits VkFlags)
(cffi:defctype VkFrontFace VkFlags)
(cffi:defctype VkImageAspectFlagBits VkFlags)
(cffi:defctype VkImageCreateFlagBits VkFlags)
(cffi:defctype VkImageLayout VkFlags)
(cffi:defctype VkImageTiling VkFlags)
(cffi:defctype VkImageType VkFlags)
(cffi:defctype VkImageUsageFlagBits VkFlags)
(cffi:defctype VkImageViewType VkFlags)
(cffi:defctype VkIndexType VkFlags)
(cffi:defctype VkIndirectCommandsLayoutUsageFlagBitsNVX VkFlags)
(cffi:defctype VkIndirectCommandsTokenTypeNVX VkFlags)
(cffi:defctype VkInternalAllocationType VkFlags)
(cffi:defctype VkLogicOp VkFlags)
(cffi:defctype VkMemoryAllocateFlagBitsKHX VkFlags)
(cffi:defctype VkMemoryHeapFlagBits VkFlags)
(cffi:defctype VkMemoryPropertyFlagBits VkFlags)
(cffi:defctype VkObjectEntryTypeNVX VkFlags)
(cffi:defctype VkObjectEntryUsageFlagBitsNVX VkFlags)
(cffi:defctype VkObjectType VkFlags)
(cffi:defctype VkPeerMemoryFeatureFlagBitsKHX VkFlags)
(cffi:defctype VkPhysicalDeviceType VkFlags)
(cffi:defctype VkPipelineBindPoint VkFlags)
(cffi:defctype VkPipelineCacheHeaderVersion VkFlags)
(cffi:defctype VkPipelineCreateFlagBits VkFlags)
(cffi:defctype VkPipelineStageFlagBits VkFlags)
(cffi:defctype VkPolygonMode VkFlags)
(cffi:defctype VkPresentModeKHR VkFlags)
(cffi:defctype VkPrimitiveTopology VkFlags)
(cffi:defctype VkQueryControlFlagBits VkFlags)
(cffi:defctype VkQueryPipelineStatisticFlagBits VkFlags)
(cffi:defctype VkQueryResultFlagBits VkFlags)
(cffi:defctype VkQueryType VkFlags)
(cffi:defctype VkQueueFlagBits VkFlags)
(cffi:defctype VkRasterizationOrderAMD VkFlags)
(cffi:defctype VkResult VkFlags)
(cffi:defctype VkSampleCountFlagBits VkFlags)
(cffi:defctype VkSamplerAddressMode VkFlags)
(cffi:defctype VkSamplerMipmapMode VkFlags)
(cffi:defctype VkShaderStageFlagBits VkFlags)
(cffi:defctype VkSharingMode VkFlags)
(cffi:defctype VkSparseImageFormatFlagBits VkFlags)
(cffi:defctype VkSparseMemoryBindFlagBits VkFlags)
(cffi:defctype VkStencilFaceFlagBits VkFlags)
(cffi:defctype VkStencilOp VkFlags)
(cffi:defctype VkStructureType VkFlags)
(cffi:defctype VkSubpassContents VkFlags)
(cffi:defctype VkSubpassDescriptionFlagBits VkFlags)
(cffi:defctype VkSurfaceCounterFlagBitsEXT VkFlags)
(cffi:defctype VkSurfaceTransformFlagBitsKHR VkFlags)
(cffi:defctype VkSwapchainCreateFlagBitsKHR VkFlags)
(cffi:defctype VkSystemAllocationScope VkFlags)
(cffi:defctype VkValidationCheckEXT VkFlags)
(cffi:defctype VkVertexInputRate VkFlags)
(cffi:defctype VkViewportCoordinateSwizzleNV VkFlags)
(cffi:defctype PFN_vkAllocationFunction :pointer)
(cffi:defctype PFN_vkDebugReportCallbackEXT :pointer)
(cffi:defctype PFN_vkFreeFunction :pointer)
(cffi:defctype PFN_vkInternalAllocationNotification :pointer)
(cffi:defctype PFN_vkInternalFreeNotification :pointer)
(cffi:defctype PFN_vkReallocationFunction :pointer)
(cffi:defctype PFN_vkVoidFunction :pointer)
(cffi:defctype VkLineRasterizationModeEXT VkFlags)

(cffi:defcstruct wl_display)
(cffi:defcstruct wl_surface)

 ;; ("defcallback x" "VkBool32"
 ;;  (("\"flags\"" "VkDebugReportFlagsEXT")
 ;;   ("\"objectType\"" "VkDebugReportObjectTypeEXT") ("\"object\"" "uint64_t")
 ;;   ("\"location\"" "size_t") ("\"messageCode\"" "int32_t")
 ;;   ("\"pLayerPrefix\"" (:POINTER "char"))
 ;;   ("\"pMessage\"/const" (:POINTER "char"))
 ;;   ("\"pUserData\"/const" (:POINTER "void"))))

 ;; ("defcallback x" ":void"
 ;;  (("\"pUserData\"" (:POINTER "void")) ("\"pMemory\"" (:POINTER "void"))))

 ;; ("defcallback x" ":void"
 ;;  (("\"pUserData\"" (:POINTER "void")) ("\"size\"" "size_t")
 ;;   ("\"allocationType\"" "VkInternalAllocationType")
 ;;   ("\"allocationScope\"" "VkSystemAllocationScope")))

 ;; ("defcallback x" ":void"
 ;;  (("\"pUserData\"" (:POINTER "void")) ("\"size\"" "size_t")
 ;;   ("\"allocationType\"" "VkInternalAllocationType")
 ;;   ("\"allocationScope\"" "VkSystemAllocationScope")))

 ;; ("defcallback x" (:POINTER ":void")
 ;;  (("\"pUserData\"" (:POINTER "void")) ("\"pOriginal\"" (:POINTER "void"))
 ;;   ("\"size\"" "size_t") ("\"alignment\"" "size_t")
 ;;   ("\"allocationScope\"" "VkSystemAllocationScope")))

 ;; ("defcallback x" ":void" NIL)

(cffi:defcstruct VkAcquireNextImageInfoKHX
  (:sType VkStructureType)#|MUST-BE :ACQUIRE-NEXT-IMAGE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:swapchain VkSwapchainKHR)#|OPAQUE T|#
  (:timeout :uint64)
  (:semaphore VkSemaphore)#|OPTIONAL (:true) OPAQUE T|#
  (:fence VkFence)#|OPTIONAL (:true) OPAQUE T|#
  (:deviceMask :uint32))

(cffi:defcstruct VkAllocationCallbacks
  (:pUserData (:pointer :void))#|OPTIONAL (:true)|#
  (:pfnAllocation PFN_vkAllocationFunction)
  (:pfnReallocation PFN_vkReallocationFunction)
  (:pfnFree PFN_vkFreeFunction)
  (:pfnInternalAllocation PFN_vkInternalAllocationNotification)#|OPTIONAL (:true)|#
  (:pfnInternalFree PFN_vkInternalFreeNotification)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkAndroidSurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :ANDROID-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkAndroidSurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:window (:pointer ANativeWindow))#|OPAQUE T|#)

(cffi:defcstruct VkApplicationInfo
  (:sType VkStructureType)#|MUST-BE :APPLICATION-INFO|#
  (:pNext (:pointer :void))
  (:pApplicationName (:pointer :char))#|OPTIONAL (:true) LEN (NULL-TERMINATED)|#
  (:applicationVersion :uint32)
  (:pEngineName (:pointer :char))#|OPTIONAL (:true) LEN (NULL-TERMINATED)|#
  (:engineVersion :uint32)
  (:apiVersion :uint32))

(cffi:defcstruct VkAttachmentDescription
  (:flags VkAttachmentDescriptionFlags)#|OPTIONAL (:true)|#
  (:format VkFormat)
  (:samples VkSampleCountFlagBits)
  (:loadOp VkAttachmentLoadOp)
  (:storeOp VkAttachmentStoreOp)
  (:stencilLoadOp VkAttachmentLoadOp)
  (:stencilStoreOp VkAttachmentStoreOp)
  (:initialLayout VkImageLayout)
  (:finalLayout VkImageLayout))

(cffi:defcstruct VkAttachmentReference
  (:attachment :uint32)
  (:layout VkImageLayout))

(cffi:defcstruct VkBindBufferMemoryInfoKHX
  (:sType VkStructureType)#|MUST-BE :BIND-BUFFER-MEMORY-INFO-KHX|#
  (:pNext (:pointer :void))
  (:buffer VkBuffer)#|OPAQUE T|#
  (:memory VkDeviceMemory)#|OPAQUE T|#
  (:memoryOffset VkDeviceSize)
  (:deviceIndexCount :uint32)#|OPTIONAL (:true)|#
  (:pDeviceIndices (:pointer :uint32))#|LEN (:deviceIndexCount)|#)

(cffi:defcstruct VkOffset2D
  (:x :int32)
  (:y :int32))

(cffi:defcstruct VkExtent2D
  (:width :uint32)
  (:height :uint32))

(cffi:defcstruct VkRect2D
  (:offset (:struct VkOffset2D))
  (:extent (:struct VkExtent2D)))

(cffi:defcstruct VkBindImageMemoryInfoKHX
  (:sType VkStructureType)#|MUST-BE :BIND-IMAGE-MEMORY-INFO-KHX|#
  (:pNext (:pointer :void))
  (:image VkImage)#|OPAQUE T|#
  (:memory VkDeviceMemory)#|OPAQUE T|#
  (:memoryOffset VkDeviceSize)
  (:deviceIndexCount :uint32)#|OPTIONAL (:true)|#
  (:pDeviceIndices (:pointer :uint32))#|LEN (:deviceIndexCount)|#
  (:SFRRectCount :uint32)#|OPTIONAL (:true)|#
  (:pSFRRects (:pointer (:struct VkRect2D)))#|LEN (:SFRRectCount)|#)

(cffi:defcstruct VkBindImageMemorySwapchainInfoKHX
  (:sType VkStructureType)#|MUST-BE :BIND-IMAGE-MEMORY-SWAPCHAIN-INFO-KHX|#
  (:pNext (:pointer :void))
  (:swapchain VkSwapchainKHR)#|OPAQUE T|#
  (:imageIndex :uint32))

(cffi:defcstruct VkSparseMemoryBind
  (:resourceOffset VkDeviceSize)
  (:size VkDeviceSize)
  (:memory VkDeviceMemory)#|OPTIONAL (:true) OPAQUE T|#
  (:memoryOffset VkDeviceSize)
  (:flags VkSparseMemoryBindFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSparseBufferMemoryBindInfo
  (:buffer VkBuffer)#|OPAQUE T|#
  (:bindCount :uint32)
  (:pBinds (:pointer (:struct VkSparseMemoryBind)))#|LEN (:bindCount)|#)

(cffi:defcstruct VkSparseImageOpaqueMemoryBindInfo
  (:image VkImage)#|OPAQUE T|#
  (:bindCount :uint32)
  (:pBinds (:pointer (:struct VkSparseMemoryBind)))#|LEN (:bindCount)|#)

(cffi:defcstruct VkImageSubresource
  (:aspectMask VkImageAspectFlags)
  (:mipLevel :uint32)
  (:arrayLayer :uint32))

(cffi:defcstruct VkOffset3D
  (:x :int32)
  (:y :int32)
  (:z :int32))

(cffi:defcstruct VkExtent3D
  (:width :uint32)
  (:height :uint32)
  (:depth :uint32))

(cffi:defcstruct VkSparseImageMemoryBind
  (:subresource (:struct VkImageSubresource))
  (:offset (:struct VkOffset3D))
  (:extent (:struct VkExtent3D))
  (:memory VkDeviceMemory)#|OPTIONAL (:true) OPAQUE T|#
  (:memoryOffset VkDeviceSize)
  (:flags VkSparseMemoryBindFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSparseImageMemoryBindInfo
  (:image VkImage)#|OPAQUE T|#
  (:bindCount :uint32)
  (:pBinds (:pointer (:struct VkSparseImageMemoryBind)))#|LEN (:bindCount)|#)

(cffi:defcstruct VkBindSparseInfo
  (:sType VkStructureType)#|MUST-BE :BIND-SPARSE-INFO|#
  (:pNext (:pointer :void))
  (:waitSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pWaitSemaphores (:pointer VkSemaphore))#|LEN (:waitSemaphoreCount) OPAQUE T|#
  (:bufferBindCount :uint32)#|OPTIONAL (:true)|#
  (:pBufferBinds (:pointer (:struct VkSparseBufferMemoryBindInfo)))#|LEN (:bufferBindCount)|#
  (:imageOpaqueBindCount :uint32)#|OPTIONAL (:true)|#
  (:pImageOpaqueBinds (:pointer (:struct VkSparseImageOpaqueMemoryBindInfo)))#|LEN (:imageOpaqueBindCount)|#
  (:imageBindCount :uint32)#|OPTIONAL (:true)|#
  (:pImageBinds (:pointer (:struct VkSparseImageMemoryBindInfo)))#|LEN (:imageBindCount)|#
  (:signalSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pSignalSemaphores (:pointer VkSemaphore))#|LEN (:signalSemaphoreCount) OPAQUE T|#)

(cffi:defcstruct VkBufferCopy
  (:srcOffset VkDeviceSize)
  (:dstOffset VkDeviceSize)
  (:size VkDeviceSize))

(cffi:defcstruct VkBufferCreateInfo
  (:sType VkStructureType)#|MUST-BE :BUFFER-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkBufferCreateFlags)#|OPTIONAL (:true)|#
  (:size VkDeviceSize)
  (:usage VkBufferUsageFlags)
  (:sharingMode VkSharingMode)
  (:queueFamilyIndexCount :uint32)#|OPTIONAL (:true)|#
  (:pQueueFamilyIndices (:pointer :uint32))#|LEN (:queueFamilyIndexCount)|#)

(cffi:defcstruct VkImageSubresourceLayers
  (:aspectMask VkImageAspectFlags)
  (:mipLevel :uint32)
  (:baseArrayLayer :uint32)
  (:layerCount :uint32))

(cffi:defcstruct VkBufferImageCopy
  (:bufferOffset VkDeviceSize)
  (:bufferRowLength :uint32)
  (:bufferImageHeight :uint32)
  (:imageSubresource (:struct VkImageSubresourceLayers))
  (:imageOffset (:struct VkOffset3D))
  (:imageExtent (:struct VkExtent3D)))

(cffi:defcstruct VkBufferMemoryBarrier
  (:sType VkStructureType)#|MUST-BE :BUFFER-MEMORY-BARRIER|#
  (:pNext (:pointer :void))
  (:srcAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:dstAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:srcQueueFamilyIndex :uint32)
  (:dstQueueFamilyIndex :uint32)
  (:buffer VkBuffer)#|OPAQUE T|#
  (:offset VkDeviceSize)
  (:size VkDeviceSize))

(cffi:defcstruct VkBufferViewCreateInfo
  (:sType VkStructureType)#|MUST-BE :BUFFER-VIEW-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkBufferViewCreateFlags)#|OPTIONAL (:true)|#
  (:buffer VkBuffer)#|OPAQUE T|#
  (:format VkFormat)
  (:offset VkDeviceSize)
  (:range VkDeviceSize))

(cffi:defcunion VkClearColorValue
  (:float32 :float :count 4)
  (:int32 :int32 :count 4)
  (:uint32 :uint32 :count 4))

(cffi:defcstruct VkClearDepthStencilValue
  (:depth :float)
  (:stencil :uint32))

(cffi:defcunion VkClearValue
  (:color (:union VkClearColorValue))
  (:depthStencil (:struct VkClearDepthStencilValue)))

(cffi:defcstruct VkClearAttachment
  (:aspectMask VkImageAspectFlags)
  (:colorAttachment :uint32)
  (:clearValue (:union VkClearValue)))

(cffi:defcstruct VkClearRect
  (:rect (:struct VkRect2D))
  (:baseArrayLayer :uint32)
  (:layerCount :uint32))

(cffi:defcstruct VkIndirectCommandsTokenNVX
  (:tokenType VkIndirectCommandsTokenTypeNVX)
  (:buffer VkBuffer)#|OPAQUE T|#
  (:offset VkDeviceSize))

(cffi:defcstruct VkCmdProcessCommandsInfoNVX
  (:sType VkStructureType)#|MUST-BE :CMD-PROCESS-COMMANDS-INFO-NVX|#
  (:pNext (:pointer :void))
  (:objectTable VkObjectTableNVX)#|OPAQUE T|#
  (:indirectCommandsLayout VkIndirectCommandsLayoutNVX)#|OPAQUE T|#
  (:indirectCommandsTokenCount :uint32)
  (:pIndirectCommandsTokens (:pointer (:struct VkIndirectCommandsTokenNVX)))#|LEN (:indirectCommandsTokenCount)|#
  (:maxSequencesCount :uint32)
  (:targetCommandBuffer VkCommandBuffer)#|OPTIONAL (:true) OPAQUE T|#
  (:sequencesCountBuffer VkBuffer)#|OPTIONAL (:true) OPAQUE T|#
  (:sequencesCountOffset VkDeviceSize)#|OPTIONAL (:true)|#
  (:sequencesIndexBuffer VkBuffer)#|OPTIONAL (:true) OPAQUE T|#
  (:sequencesIndexOffset VkDeviceSize)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkCmdReserveSpaceForCommandsInfoNVX
  (:sType VkStructureType)#|MUST-BE :CMD-RESERVE-SPACE-FOR-COMMANDS-INFO-NVX|#
  (:pNext (:pointer :void))
  (:objectTable VkObjectTableNVX)#|OPAQUE T|#
  (:indirectCommandsLayout VkIndirectCommandsLayoutNVX)#|OPAQUE T|#
  (:maxSequencesCount :uint32))

(cffi:defcstruct VkCommandBufferAllocateInfo
  (:sType VkStructureType)#|MUST-BE :COMMAND-BUFFER-ALLOCATE-INFO|#
  (:pNext (:pointer :void))
  (:commandPool VkCommandPool)#|OPAQUE T|#
  (:level VkCommandBufferLevel)
  (:commandBufferCount :uint32))

(cffi:defcstruct VkCommandBufferInheritanceInfo
  (:sType VkStructureType)#|MUST-BE :COMMAND-BUFFER-INHERITANCE-INFO|#
  (:pNext (:pointer :void))
  (:renderPass VkRenderPass)#|OPTIONAL (:true) OPAQUE T|#
  (:subpass :uint32)
  (:framebuffer VkFramebuffer)#|OPTIONAL (:true) OPAQUE T|#
  (:occlusionQueryEnable VkBool32)
  (:queryFlags VkQueryControlFlags)#|OPTIONAL (:true)|#
  (:pipelineStatistics VkQueryPipelineStatisticFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkCommandBufferBeginInfo
  (:sType VkStructureType)#|MUST-BE :COMMAND-BUFFER-BEGIN-INFO|#
  (:pNext (:pointer :void))
  (:flags VkCommandBufferUsageFlags)#|OPTIONAL (:true)|#
  (:pInheritanceInfo (:pointer (:struct VkCommandBufferInheritanceInfo)))#|OPTIONAL (:true)|#)

(cffi:defcstruct VkCommandPoolCreateInfo
  (:sType VkStructureType)#|MUST-BE :COMMAND-POOL-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkCommandPoolCreateFlags)#|OPTIONAL (:true)|#
  (:queueFamilyIndex :uint32))

(cffi:defcstruct VkComponentMapping
  (:r VkComponentSwizzle)
  (:g VkComponentSwizzle)
  (:b VkComponentSwizzle)
  (:a VkComponentSwizzle))

(cffi:defcstruct VkSpecializationMapEntry
  (:constantID :uint32)
  (:offset :uint32)
  (:size size-t))

(cffi:defcstruct VkSpecializationInfo
  (:mapEntryCount :uint32)#|OPTIONAL (:true)|#
  (:pMapEntries (:pointer (:struct VkSpecializationMapEntry)))#|LEN (:mapEntryCount)|#
  (:dataSize size-t)#|OPTIONAL (:true)|#
  (:pData (:pointer :void))#|LEN (:dataSize)|#)

(cffi:defcstruct VkPipelineShaderStageCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-SHADER-STAGE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineShaderStageCreateFlags)#|OPTIONAL (:true)|#
  (:stage VkShaderStageFlagBits)
  (:module VkShaderModule)#|OPAQUE T|#
  (:pName (:pointer :char))#|LEN (NULL-TERMINATED)|#
  (:pSpecializationInfo (:pointer (:struct VkSpecializationInfo)))#|OPTIONAL (:true)|#)

(cffi:defcstruct VkComputePipelineCreateInfo
  (:sType VkStructureType)#|MUST-BE :COMPUTE-PIPELINE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineCreateFlags)#|OPTIONAL (:true)|#
  (:stage (:struct VkPipelineShaderStageCreateInfo))
  (:layout VkPipelineLayout)#|OPAQUE T|#
  (:basePipelineHandle VkPipeline)#|OPTIONAL (:true) OPAQUE T|#
  (:basePipelineIndex :int32))

(cffi:defcstruct VkCopyDescriptorSet
  (:sType VkStructureType)#|MUST-BE :COPY-DESCRIPTOR-SET|#
  (:pNext (:pointer :void))
  (:srcSet VkDescriptorSet)#|OPAQUE T|#
  (:srcBinding :uint32)
  (:srcArrayElement :uint32)
  (:dstSet VkDescriptorSet)#|OPAQUE T|#
  (:dstBinding :uint32)
  (:dstArrayElement :uint32)
  (:descriptorCount :uint32))

(cffi:defcstruct VkD3D12FenceSubmitInfoKHX
  (:sType VkStructureType)#|MUST-BE :D3D12-FENCE-SUBMIT-INFO-KHX|#
  (:pNext (:pointer :void))
  (:waitSemaphoreValuesCount :uint32)#|OPTIONAL (:true)|#
  (:pWaitSemaphoreValues (:pointer :uint64))#|OPTIONAL (:true) LEN (:waitSemaphoreValuesCount)|#
  (:signalSemaphoreValuesCount :uint32)#|OPTIONAL (:true)|#
  (:pSignalSemaphoreValues (:pointer :uint64))#|OPTIONAL (:true) LEN (:signalSemaphoreValuesCount)|#)

(cffi:defcstruct VkDebugMarkerMarkerInfoEXT
  (:sType VkStructureType)#|MUST-BE :DEBUG-MARKER-MARKER-INFO-EXT|#
  (:pNext (:pointer :void))
  (:pMarkerName (:pointer :char))#|LEN (NULL-TERMINATED)|#
  (:color :float :count 4)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkDebugMarkerObjectNameInfoEXT
  (:sType VkStructureType)#|MUST-BE :DEBUG-MARKER-OBJECT-NAME-INFO-EXT|#
  (:pNext (:pointer :void))
  (:objectType VkDebugReportObjectTypeEXT)
  (:object :uint64)
  (:pObjectName (:pointer :char))#|LEN (NULL-TERMINATED)|#)

(cffi:defcstruct VkDebugMarkerObjectTagInfoEXT
  (:sType VkStructureType)#|MUST-BE :DEBUG-MARKER-OBJECT-TAG-INFO-EXT|#
  (:pNext (:pointer :void))
  (:objectType VkDebugReportObjectTypeEXT)
  (:object :uint64)
  (:tagName :uint64)
  (:tagSize size-t)
  (:pTag (:pointer :void))#|LEN (:tagSize)|#)

(cffi:defcstruct VkDebugReportCallbackCreateInfoEXT
  (:sType VkStructureType)#|MUST-BE :DEBUG-REPORT-CALLBACK-CREATE-INFO-EXT|#
  (:pNext (:pointer :void))
  (:flags VkDebugReportFlagsEXT)#|OPTIONAL (:true)|#
  (:pfnCallback PFN_vkDebugReportCallbackEXT)
  (:pUserData (:pointer :void))#|OPTIONAL (:true)|#)

(cffi:defcstruct VkDedicatedAllocationBufferCreateInfoNV
  (:sType VkStructureType)#|MUST-BE :DEDICATED-ALLOCATION-BUFFER-CREATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:dedicatedAllocation VkBool32))

(cffi:defcstruct VkDedicatedAllocationImageCreateInfoNV
  (:sType VkStructureType)#|MUST-BE :DEDICATED-ALLOCATION-IMAGE-CREATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:dedicatedAllocation VkBool32))

(cffi:defcstruct VkDedicatedAllocationMemoryAllocateInfoNV
  (:sType VkStructureType)#|MUST-BE :DEDICATED-ALLOCATION-MEMORY-ALLOCATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:image VkImage)#|OPTIONAL (:true) OPAQUE T|#
  (:buffer VkBuffer)#|OPTIONAL (:true) OPAQUE T|#)

(cffi:defcstruct VkDescriptorBufferInfo
  (:buffer VkBuffer)#|OPAQUE T|#
  (:offset VkDeviceSize)
  (:range VkDeviceSize))

(cffi:defcstruct VkDescriptorImageInfo
  (:sampler VkSampler)#|OPAQUE T|#
  (:imageView VkImageView)#|OPAQUE T|#
  (:imageLayout VkImageLayout))

(cffi:defcstruct VkDescriptorPoolSize
  (:type VkDescriptorType)
  (:descriptorCount :uint32))

(cffi:defcstruct VkDescriptorPoolCreateInfo
  (:sType VkStructureType)#|MUST-BE :DESCRIPTOR-POOL-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkDescriptorPoolCreateFlags)#|OPTIONAL (:true)|#
  (:maxSets :uint32)
  (:poolSizeCount :uint32)
  (:pPoolSizes (:pointer (:struct VkDescriptorPoolSize)))#|LEN (:poolSizeCount)|#)

(cffi:defcstruct VkDescriptorSetAllocateInfo
  (:sType VkStructureType)#|MUST-BE :DESCRIPTOR-SET-ALLOCATE-INFO|#
  (:pNext (:pointer :void))
  (:descriptorPool VkDescriptorPool)#|OPAQUE T|#
  (:descriptorSetCount :uint32)
  (:pSetLayouts (:pointer VkDescriptorSetLayout))#|LEN (:descriptorSetCount) OPAQUE T|#)

(cffi:defcstruct VkDescriptorSetLayoutBinding
  (:binding :uint32)
  (:descriptorType VkDescriptorType)
  (:descriptorCount :uint32)#|OPTIONAL (:true)|#
  (:stageFlags VkShaderStageFlags)
  (:pImmutableSamplers (:pointer VkSampler))#|OPTIONAL (:true) LEN (:descriptorCount) OPAQUE T|#)

(cffi:defcstruct VkDescriptorSetLayoutCreateInfo
  (:sType VkStructureType)#|MUST-BE :DESCRIPTOR-SET-LAYOUT-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkDescriptorSetLayoutCreateFlags)#|OPTIONAL (:true)|#
  (:bindingCount :uint32)#|OPTIONAL (:true)|#
  (:pBindings (:pointer (:struct VkDescriptorSetLayoutBinding)))#|LEN (:bindingCount)|#)

(cffi:defcstruct VkDescriptorUpdateTemplateEntryKHR
  (:dstBinding :uint32)
  (:dstArrayElement :uint32)
  (:descriptorCount :uint32)
  (:descriptorType VkDescriptorType)
  (:offset size-t)
  (:stride size-t))

(cffi:defcstruct VkDescriptorUpdateTemplateCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :DESCRIPTOR-UPDATE-TEMPLATE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkDescriptorUpdateTemplateCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:descriptorUpdateEntryCount :uint32)
  (:pDescriptorUpdateEntries (:pointer
                             (::struct VkDescriptorUpdateTemplateEntryKHR)))#|LEN (:descriptorUpdateEntryCount)|#
  (:templateType VkDescriptorUpdateTemplateTypeKHR)
  (:descriptorSetLayout VkDescriptorSetLayout)#|OPTIONAL (:true) OPAQUE T|#
  (:pipelineBindPoint VkPipelineBindPoint)#|OPTIONAL (:true)|#
  (:pipelineLayout VkPipelineLayout)#|OPTIONAL (:true) OPAQUE T|#
  (:set :uint32)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkDeviceQueueCreateInfo
  (:sType VkStructureType)#|MUST-BE :DEVICE-QUEUE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkDeviceQueueCreateFlags)#|OPTIONAL (:true)|#
  (:queueFamilyIndex :uint32)
  (:queueCount :uint32)
  (:pQueuePriorities (:pointer :float))#|LEN (:queueCount)|#)

(cffi:defcstruct VkPhysicalDeviceFeatures
  (:robustBufferAccess VkBool32)
  (:fullDrawIndexUint32 VkBool32)
  (:imageCubeArray VkBool32)
  (:independentBlend VkBool32)
  (:geometryShader VkBool32)
  (:tessellationShader VkBool32)
  (:sampleRateShading VkBool32)
  (:dualSrcBlend VkBool32)
  (:logicOp VkBool32)
  (:multiDrawIndirect VkBool32)
  (:drawIndirectFirstInstance VkBool32)
  (:depthClamp VkBool32)
  (:depthBiasClamp VkBool32)
  (:fillModeNonSolid VkBool32)
  (:depthBounds VkBool32)
  (:wideLines VkBool32)
  (:largePoints VkBool32)
  (:alphaToOne VkBool32)
  (:multiViewport VkBool32)
  (:samplerAnisotropy VkBool32)
  (:textureCompressionETC2 VkBool32)
  (:textureCompressionASTC_LDR VkBool32)
  (:textureCompressionBC VkBool32)
  (:occlusionQueryPrecise VkBool32)
  (:pipelineStatisticsQuery VkBool32)
  (:vertexPipelineStoresAndAtomics VkBool32)
  (:fragmentStoresAndAtomics VkBool32)
  (:shaderTessellationAndGeometryPointSize VkBool32)
  (:shaderImageGatherExtended VkBool32)
  (:shaderStorageImageExtendedFormats VkBool32)
  (:shaderStorageImageMultisample VkBool32)
  (:shaderStorageImageReadWithoutFormat VkBool32)
  (:shaderStorageImageWriteWithoutFormat VkBool32)
  (:shaderUniformBufferArrayDynamicIndexing VkBool32)
  (:shaderSampledImageArrayDynamicIndexing VkBool32)
  (:shaderStorageBufferArrayDynamicIndexing VkBool32)
  (:shaderStorageImageArrayDynamicIndexing VkBool32)
  (:shaderClipDistance VkBool32)
  (:shaderCullDistance VkBool32)
  (:shaderFloat64 VkBool32)
  (:shaderInt64 VkBool32)
  (:shaderInt16 VkBool32)
  (:shaderResourceResidency VkBool32)
  (:shaderResourceMinLod VkBool32)
  (:sparseBinding VkBool32)
  (:sparseResidencyBuffer VkBool32)
  (:sparseResidencyImage2D VkBool32)
  (:sparseResidencyImage3D VkBool32)
  (:sparseResidency2Samples VkBool32)
  (:sparseResidency4Samples VkBool32)
  (:sparseResidency8Samples VkBool32)
  (:sparseResidency16Samples VkBool32)
  (:sparseResidencyAliased VkBool32)
  (:variableMultisampleRate VkBool32)
  (:inheritedQueries VkBool32))

(cffi:defcstruct VkDeviceCreateInfo
  (:sType VkStructureType)#|MUST-BE :DEVICE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkDeviceCreateFlags)#|OPTIONAL (:true)|#
  (:queueCreateInfoCount :uint32)
  (:pQueueCreateInfos (:pointer (:struct VkDeviceQueueCreateInfo)))#|LEN (:queueCreateInfoCount)|#
  (:enabledLayerCount :uint32)#|OPTIONAL (:true)|#
  (:ppEnabledLayerNames (:pointer (:pointer :char)))#|LEN (:enabledLayerCount
                                                          NULL-TERMINATED)|#
  (:enabledExtensionCount :uint32)#|OPTIONAL (:true)|#
  (:ppEnabledExtensionNames (:pointer (:pointer :char)))#|LEN (:enabledExtensionCount
                                                              NULL-TERMINATED)|#
  (:pEnabledFeatures (:pointer (:struct VkPhysicalDeviceFeatures)))#|OPTIONAL (:true)|#)

(cffi:defcstruct VkDeviceEventInfoEXT
  (:sType VkStructureType)#|MUST-BE :DEVICE-EVENT-INFO-EXT|#
  (:pNext (:pointer :void))
  (:deviceEvent VkDeviceEventTypeEXT))

(cffi:defcstruct VkDeviceGeneratedCommandsFeaturesNVX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GENERATED-COMMANDS-FEATURES-NVX|#
  (:pNext (:pointer :void))
  (:computeBindingPointSupport VkBool32))

(cffi:defcstruct VkDeviceGeneratedCommandsLimitsNVX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GENERATED-COMMANDS-LIMITS-NVX|#
  (:pNext (:pointer :void))
  (:maxIndirectCommandsLayoutTokenCount :uint32)
  (:maxObjectEntryCounts :uint32)
  (:minSequenceCountBufferOffsetAlignment :uint32)
  (:minSequenceIndexBufferOffsetAlignment :uint32)
  (:minCommandsTokenBufferOffsetAlignment :uint32))

(cffi:defcstruct VkDeviceGroupBindSparseInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-BIND-SPARSE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:resourceDeviceIndex :uint32)
  (:memoryDeviceIndex :uint32))

(cffi:defcstruct VkDeviceGroupCommandBufferBeginInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-COMMAND-BUFFER-BEGIN-INFO-KHX|#
  (:pNext (:pointer :void))
  (:deviceMask :uint32))

(cffi:defcstruct VkDeviceGroupDeviceCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-DEVICE-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:physicalDeviceCount :uint32)#|OPTIONAL (:true)|#
  (:pPhysicalDevices (:pointer VkPhysicalDevice))#|LEN (:physicalDeviceCount) OPAQUE T|#)

(cffi:defcstruct VkDeviceGroupPresentCapabilitiesKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-PRESENT-CAPABILITIES-KHX|#
  (:pNext (:pointer :void))
  (:presentMask :uint32 :count 32)
  (:modes VkDeviceGroupPresentModeFlagsKHX))

(cffi:defcstruct VkDeviceGroupPresentInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-PRESENT-INFO-KHX|#
  (:pNext (:pointer :void))
  (:swapchainCount :uint32)#|OPTIONAL (:true)|#
  (:pDeviceMasks (:pointer :uint32))#|LEN (:swapchainCount)|#
  (:mode VkDeviceGroupPresentModeFlagBitsKHX))

(cffi:defcstruct VkDeviceGroupRenderPassBeginInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-RENDER-PASS-BEGIN-INFO-KHX|#
  (:pNext (:pointer :void))
  (:deviceMask :uint32)
  (:deviceRenderAreaCount :uint32)#|OPTIONAL (:true)|#
  (:pDeviceRenderAreas (:pointer (:struct VkRect2D)))#|LEN (:deviceRenderAreaCount)|#)

(cffi:defcstruct VkDeviceGroupSubmitInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-SUBMIT-INFO-KHX|#
  (:pNext (:pointer :void))
  (:waitSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pWaitSemaphoreDeviceIndices (:pointer :uint32))#|LEN (:waitSemaphoreCount)|#
  (:commandBufferCount :uint32)#|OPTIONAL (:true)|#
  (:pCommandBufferDeviceMasks (:pointer :uint32))#|LEN (:commandBufferCount)|#
  (:signalSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pSignalSemaphoreDeviceIndices (:pointer :uint32))#|LEN (:signalSemaphoreCount)|#)

(cffi:defcstruct VkDeviceGroupSwapchainCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :DEVICE-GROUP-SWAPCHAIN-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:modes VkDeviceGroupPresentModeFlagsKHX))

(cffi:defcstruct VkDispatchIndirectCommand
  (:x :uint32)
  (:y :uint32)
  (:z :uint32))

(cffi:defcstruct VkDisplayEventInfoEXT
  (:sType VkStructureType)#|MUST-BE :DISPLAY-EVENT-INFO-EXT|#
  (:pNext (:pointer :void))
  (:displayEvent VkDisplayEventTypeEXT))

(cffi:defcstruct VkDisplayModeParametersKHR
  (:visibleRegion (:struct VkExtent2D))
  (:refreshRate :uint32))

(cffi:defcstruct VkDisplayModeCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :DISPLAY-MODE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkDisplayModeCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:parameters (:struct VkDisplayModeParametersKHR)))

(cffi:defcstruct VkDisplayModePropertiesKHR
  (:displayMode VkDisplayModeKHR)#|OPAQUE T|#
  (:parameters (:struct VkDisplayModeParametersKHR)))

(cffi:defcstruct VkDisplayPlaneCapabilitiesKHR
  (:supportedAlpha VkDisplayPlaneAlphaFlagsKHR)#|OPTIONAL (:true)|#
  (:minSrcPosition (:struct VkOffset2D))
  (:maxSrcPosition (:struct VkOffset2D))
  (:minSrcExtent (:struct VkExtent2D))
  (:maxSrcExtent (:struct VkExtent2D))
  (:minDstPosition (:struct VkOffset2D))
  (:maxDstPosition (:struct VkOffset2D))
  (:minDstExtent (:struct VkExtent2D))
  (:maxDstExtent (:struct VkExtent2D)))

(cffi:defcstruct VkDisplayPlanePropertiesKHR
  (:currentDisplay VkDisplayKHR)#|OPAQUE T|#
  (:currentStackIndex :uint32))

(cffi:defcstruct VkDisplayPowerInfoEXT
  (:sType VkStructureType)#|MUST-BE :DISPLAY-POWER-INFO-EXT|#
  (:pNext (:pointer :void))
  (:powerState VkDisplayPowerStateEXT))

(cffi:defcstruct VkDisplayPresentInfoKHR
  (:sType VkStructureType)#|MUST-BE :DISPLAY-PRESENT-INFO-KHR|#
  (:pNext (:pointer :void))
  (:srcRect (:struct VkRect2D))
  (:dstRect (:struct VkRect2D))
  (:persistent VkBool32))

(cffi:defcstruct VkDisplayPropertiesKHR
  (:display VkDisplayKHR)#|OPAQUE T|#
  (:displayName (:pointer :char))#|LEN (NULL-TERMINATED)|#
  (:physicalDimensions (:struct VkExtent2D))
  (:physicalResolution (:struct VkExtent2D))
  (:supportedTransforms VkSurfaceTransformFlagsKHR)#|OPTIONAL (:true)|#
  (:planeReorderPossible VkBool32)
  (:persistentContent VkBool32))

(cffi:defcstruct VkDisplaySurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :DISPLAY-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkDisplaySurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:displayMode VkDisplayModeKHR)#|OPAQUE T|#
  (:planeIndex :uint32)
  (:planeStackIndex :uint32)
  (:transform VkSurfaceTransformFlagBitsKHR)
  (:globalAlpha :float)
  (:alphaMode VkDisplayPlaneAlphaFlagBitsKHR)
  (:imageExtent (:struct VkExtent2D)))

(cffi:defcstruct VkDrawIndexedIndirectCommand
  (:indexCount :uint32)
  (:instanceCount :uint32)
  (:firstIndex :uint32)
  (:vertexOffset :int32)
  (:firstInstance :uint32))

(cffi:defcstruct VkDrawIndirectCommand
  (:vertexCount :uint32)
  (:instanceCount :uint32)
  (:firstVertex :uint32)
  (:firstInstance :uint32))

(cffi:defcstruct VkEventCreateInfo
  (:sType VkStructureType)#|MUST-BE :EVENT-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkEventCreateFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExportMemoryAllocateInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXPORT-MEMORY-ALLOCATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalMemoryHandleTypeFlagsKHX)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExportMemoryAllocateInfoNV
  (:sType VkStructureType)#|MUST-BE :EXPORT-MEMORY-ALLOCATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalMemoryHandleTypeFlagsNV)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExportMemoryWin32HandleInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXPORT-MEMORY-WIN32-HANDLE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:pAttributes (:pointer SECURITY_ATTRIBUTES))#|OPTIONAL (:true)|#
  (:dwAccess DWORD)
  (:name LPCWSTR))

(cffi:defcstruct VkExportMemoryWin32HandleInfoNV
  (:sType VkStructureType)#|MUST-BE :EXPORT-MEMORY-WIN32-HANDLE-INFO-NV|#
  (:pNext (:pointer :void))
  (:pAttributes (:pointer SECURITY_ATTRIBUTES))#|OPTIONAL (:true)|#
  (:dwAccess DWORD)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExportSemaphoreCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXPORT-SEMAPHORE-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalSemaphoreHandleTypeFlagsKHX)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExportSemaphoreWin32HandleInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXPORT-SEMAPHORE-WIN32-HANDLE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:pAttributes (:pointer SECURITY_ATTRIBUTES))#|OPTIONAL (:true)|#
  (:dwAccess DWORD)
  (:name LPCWSTR))

(cffi:defcstruct VkExtensionProperties
  (:extensionName :char :count 256)
  (:specVersion :uint32))

(cffi:defcstruct VkExternalMemoryPropertiesKHX
  (:externalMemoryFeatures VkExternalMemoryFeatureFlagsKHX)
  (:exportFromImportedHandleTypes VkExternalMemoryHandleTypeFlagsKHX)#|OPTIONAL (:true)|#
  (:compatibleHandleTypes VkExternalMemoryHandleTypeFlagsKHX))

(cffi:defcstruct VkExternalBufferPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-BUFFER-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:externalMemoryProperties (:struct VkExternalMemoryPropertiesKHX)))

(cffi:defcstruct VkExternalImageFormatPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-IMAGE-FORMAT-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:externalMemoryProperties (:struct VkExternalMemoryPropertiesKHX)))

(cffi:defcstruct VkImageFormatProperties
  (:maxExtent (:struct VkExtent3D))
  (:maxMipLevels :uint32)
  (:maxArrayLayers :uint32)
  (:sampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:maxResourceSize VkDeviceSize))

(cffi:defcstruct VkExternalImageFormatPropertiesNV
  (:imageFormatProperties (:struct VkImageFormatProperties))
  (:externalMemoryFeatures VkExternalMemoryFeatureFlagsNV)#|OPTIONAL (:true)|#
  (:exportFromImportedHandleTypes VkExternalMemoryHandleTypeFlagsNV)#|OPTIONAL (:true)|#
  (:compatibleHandleTypes VkExternalMemoryHandleTypeFlagsNV)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExternalMemoryBufferCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-MEMORY-BUFFER-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalMemoryHandleTypeFlagsKHX)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExternalMemoryImageCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-MEMORY-IMAGE-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalMemoryHandleTypeFlagsKHX))

(cffi:defcstruct VkExternalMemoryImageCreateInfoNV
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-MEMORY-IMAGE-CREATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:handleTypes VkExternalMemoryHandleTypeFlagsNV)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkExternalSemaphorePropertiesKHX
  (:sType VkStructureType)#|MUST-BE :EXTERNAL-SEMAPHORE-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:exportFromImportedHandleTypes VkExternalSemaphoreHandleTypeFlagsKHX)
  (:compatibleHandleTypes VkExternalSemaphoreHandleTypeFlagsKHX)
  (:externalSemaphoreFeatures VkExternalSemaphoreFeatureFlagsKHX)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkFenceCreateInfo
  (:sType VkStructureType)#|MUST-BE :FENCE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkFenceCreateFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkFormatProperties
  (:linearTilingFeatures VkFormatFeatureFlags)#|OPTIONAL (:true)|#
  (:optimalTilingFeatures VkFormatFeatureFlags)#|OPTIONAL (:true)|#
  (:bufferFeatures VkFormatFeatureFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkFormatProperties2KHR
  (:sType VkStructureType)#|MUST-BE :FORMAT-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:formatProperties (:struct VkFormatProperties)))

(cffi:defcstruct VkFramebufferCreateInfo
  (:sType VkStructureType)#|MUST-BE :FRAMEBUFFER-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkFramebufferCreateFlags)#|OPTIONAL (:true)|#
  (:renderPass VkRenderPass)#|OPAQUE T|#
  (:attachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pAttachments (:pointer VkImageView))#|LEN (:attachmentCount) OPAQUE T|#
  (:width :uint32)
  (:height :uint32)
  (:layers :uint32))

(cffi:defcstruct VkVertexInputBindingDescription
  (:binding :uint32)
  (:stride :uint32)
  (:inputRate VkVertexInputRate))

(cffi:defcstruct VkVertexInputAttributeDescription
  (:location :uint32)
  (:binding :uint32)
  (:format VkFormat)
  (:offset :uint32))

(cffi:defcstruct VkPipelineVertexInputStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-VERTEX-INPUT-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineVertexInputStateCreateFlags)#|OPTIONAL (:true)|#
  (:vertexBindingDescriptionCount :uint32)#|OPTIONAL (:true)|#
  (:pVertexBindingDescriptions (:pointer
                               (::struct VkVertexInputBindingDescription)))#|LEN (:vertexBindingDescriptionCount)|#
  (:vertexAttributeDescriptionCount :uint32)#|OPTIONAL (:true)|#
  (:pVertexAttributeDescriptions (:pointer
                                 (::struct VkVertexInputAttributeDescription)))#|LEN (:vertexAttributeDescriptionCount)|#)

(cffi:defcstruct VkPipelineInputAssemblyStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-INPUT-ASSEMBLY-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineInputAssemblyStateCreateFlags)#|OPTIONAL (:true)|#
  (:topology VkPrimitiveTopology)
  (:primitiveRestartEnable VkBool32))

(cffi:defcstruct VkPipelineTessellationStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-TESSELLATION-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineTessellationStateCreateFlags)#|OPTIONAL (:true)|#
  (:patchControlPoints :uint32))

(cffi:defcstruct VkViewport
  (:x :float)
  (:y :float)
  (:width :float)
  (:height :float)
  (:minDepth :float)
  (:maxDepth :float))

(cffi:defcstruct VkPipelineViewportStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-VIEWPORT-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineViewportStateCreateFlags)#|OPTIONAL (:true)|#
  (:viewportCount :uint32)
  (:pViewports (:pointer (:struct VkViewport)))#|OPTIONAL (:true) LEN (:viewportCount)|#
  (:scissorCount :uint32)
  (:pScissors (:pointer (:struct VkRect2D)))#|OPTIONAL (:true) LEN (:scissorCount)|#)

(cffi:defcstruct VkPipelineRasterizationStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-RASTERIZATION-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineRasterizationStateCreateFlags)#|OPTIONAL (:true)|#
  (:depthClampEnable VkBool32)
  (:rasterizerDiscardEnable VkBool32)
  (:polygonMode VkPolygonMode)
  (:cullMode VkCullModeFlags)#|OPTIONAL (:true)|#
  (:frontFace VkFrontFace)
  (:depthBiasEnable VkBool32)
  (:depthBiasConstantFactor :float)
  (:depthBiasClamp :float)
  (:depthBiasSlopeFactor :float)
  (:lineWidth :float))

(cl:defconstant VK_LINE_RASTERIZATION_MODE_DEFAULT_EXT 0)
(cl:defconstant VK_LINE_RASTERIZATION_MODE_RECTANGULAR_EXT 1)
(cl:defconstant VK_LINE_RASTERIZATION_MODE_BRESENHAM_EXT 2)
(cl:defconstant VK_LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH_EXT 3)

(cffi:defcstruct VkPipelineRasterizationLineStateCreateInfoEXT
  (:sType VkStructureType)
  (:pNext (:pointer :void))
  (:lineRasterizationMode VkLineRasterizationModeEXT)
  (:stippledLineEnable VkBool32)
  (:lineStippleFactor :uint32)
  (:lineStipplePattern :unsigned-short))

(cffi:defcstruct VkPhysicalDeviceLineRasterizationFeaturesEXT
  (:sType VkStructureType)
  (:pNext (:pointer :void))
  (:rectangularLines VkBool32)
  (:bresenhamLines VkBool32)
  (:smoothLines VkBool32)
  (:stippledRectangularLines VkBool32)
  (:stippledBresenhamLines VkBool32)
  (:stippledSmoothLines VkBool32))

(cffi:defcstruct VkPipelineMultisampleStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-MULTISAMPLE-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineMultisampleStateCreateFlags)#|OPTIONAL (:true)|#
  (:rasterizationSamples VkSampleCountFlagBits)
  (:sampleShadingEnable VkBool32)
  (:minSampleShading :float)
  (:pSampleMask (:pointer VkSampleMask))#|OPTIONAL (:true) LEN (latexmath:[\lceil{\mathit{rasterizationSamples} \over 32}\rceil])|#
  (:alphaToCoverageEnable VkBool32)
  (:alphaToOneEnable VkBool32))

(cffi:defcstruct VkStencilOpState
  (:failOp VkStencilOp)
  (:passOp VkStencilOp)
  (:depthFailOp VkStencilOp)
  (:compareOp VkCompareOp)
  (:compareMask :uint32)
  (:writeMask :uint32)
  (:reference :uint32))

(cffi:defcstruct VkPipelineDepthStencilStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-DEPTH-STENCIL-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineDepthStencilStateCreateFlags)#|OPTIONAL (:true)|#
  (:depthTestEnable VkBool32)
  (:depthWriteEnable VkBool32)
  (:depthCompareOp VkCompareOp)
  (:depthBoundsTestEnable VkBool32)
  (:stencilTestEnable VkBool32)
  (:front (:struct VkStencilOpState))
  (:back (:struct VkStencilOpState))
  (:minDepthBounds :float)
  (:maxDepthBounds :float))

(cffi:defcstruct VkPipelineColorBlendAttachmentState
  (:blendEnable VkBool32)
  (:srcColorBlendFactor VkBlendFactor)
  (:dstColorBlendFactor VkBlendFactor)
  (:colorBlendOp VkBlendOp)
  (:srcAlphaBlendFactor VkBlendFactor)
  (:dstAlphaBlendFactor VkBlendFactor)
  (:alphaBlendOp VkBlendOp)
  (:colorWriteMask VkColorComponentFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkPipelineColorBlendStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-COLOR-BLEND-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineColorBlendStateCreateFlags)#|OPTIONAL (:true)|#
  (:logicOpEnable VkBool32)
  (:logicOp VkLogicOp)
  (:attachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pAttachments (:pointer (:struct VkPipelineColorBlendAttachmentState)))#|LEN (:attachmentCount)|#
  (:blendConstants :float :count 4))

(cffi:defcstruct VkPipelineDynamicStateCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-DYNAMIC-STATE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineDynamicStateCreateFlags)#|OPTIONAL (:true)|#
  (:dynamicStateCount :uint32)
  (:pDynamicStates (:pointer VkDynamicState))#|LEN (:dynamicStateCount)|#)

(cffi:defcstruct VkGraphicsPipelineCreateInfo
  (:sType VkStructureType)#|MUST-BE :GRAPHICS-PIPELINE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineCreateFlags)#|OPTIONAL (:true)|#
  (:stageCount :uint32)
  (:pStages (:pointer (:struct VkPipelineShaderStageCreateInfo)))#|LEN (:stageCount)|#
  (:pVertexInputState (:pointer (:struct VkPipelineVertexInputStateCreateInfo)))
  (:pInputAssemblyState (:pointer
                        (::struct VkPipelineInputAssemblyStateCreateInfo)))
  (:pTessellationState (:pointer (:struct VkPipelineTessellationStateCreateInfo)))#|OPTIONAL (:true)|#
  (:pViewportState (:pointer (:struct VkPipelineViewportStateCreateInfo)))#|OPTIONAL (:true)|#
  (:pRasterizationState (:pointer
                        (::struct VkPipelineRasterizationStateCreateInfo)))
  (:pMultisampleState (:pointer (:struct VkPipelineMultisampleStateCreateInfo)))#|OPTIONAL (:true)|#
  (:pDepthStencilState (:pointer (:struct VkPipelineDepthStencilStateCreateInfo)))#|OPTIONAL (:true)|#
  (:pColorBlendState (:pointer (:struct VkPipelineColorBlendStateCreateInfo)))#|OPTIONAL (:true)|#
  (:pDynamicState (:pointer (:struct VkPipelineDynamicStateCreateInfo)))#|OPTIONAL (:true)|#
  (:layout VkPipelineLayout)#|OPAQUE T|#
  (:renderPass VkRenderPass)#|OPAQUE T|#
  (:subpass :uint32)
  (:basePipelineHandle VkPipeline)#|OPTIONAL (:true) OPAQUE T|#
  (:basePipelineIndex :int32))

(cffi:defcstruct VkXYColorEXT
  (:x :float)
  (:y :float))

(cffi:defcstruct VkHdrMetadataEXT
  (:sType VkStructureType)#|MUST-BE :HDR-METADATA-EXT|#
  (:pNext (:pointer :void))
  (:displayPrimaryRed (:struct VkXYColorEXT))
  (:displayPrimaryGreen (:struct VkXYColorEXT))
  (:displayPrimaryBlue (:struct VkXYColorEXT))
  (:whitePoint (:struct VkXYColorEXT))
  (:maxLuminance :float)
  (:minLuminance :float)
  (:maxContentLightLevel :float)
  (:maxFrameAverageLightLevel :float))

(cffi:defcstruct VkIOSSurfaceCreateInfoMVK
  (:sType VkStructureType)#|MUST-BE :IOS-SURFACE-CREATE-INFO-MVK|#
  (:pNext (:pointer :void))
  (:flags VkIOSSurfaceCreateFlagsMVK)#|OPTIONAL (:true)|#
  (:pView (:pointer :void)))

(cffi:defcstruct VkImageBlit
  (:srcSubresource (:struct VkImageSubresourceLayers))
  (:srcOffsets (:struct VkOffset3D) :count 2)
  (:dstSubresource (:struct VkImageSubresourceLayers))
  (:dstOffsets (:struct VkOffset3D) :count 2))

(cffi:defcstruct VkImageCopy
  (:srcSubresource (:struct VkImageSubresourceLayers))
  (:srcOffset (:struct VkOffset3D))
  (:dstSubresource (:struct VkImageSubresourceLayers))
  (:dstOffset (:struct VkOffset3D))
  (:extent (:struct VkExtent3D)))

(cffi:defcstruct VkImageCreateInfo
  (:sType VkStructureType)#|MUST-BE :IMAGE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkImageCreateFlags)#|OPTIONAL (:true)|#
  (:imageType VkImageType)
  (:format VkFormat)
  (:extent (:struct VkExtent3D))
  (:mipLevels :uint32)
  (:arrayLayers :uint32)
  (:samples VkSampleCountFlagBits)
  (:tiling VkImageTiling)
  (:usage VkImageUsageFlags)
  (:sharingMode VkSharingMode)
  (:queueFamilyIndexCount :uint32)#|OPTIONAL (:true)|#
  (:pQueueFamilyIndices (:pointer :uint32))#|LEN (:queueFamilyIndexCount)|#
  (:initialLayout VkImageLayout))

(cffi:defcstruct VkImageFormatProperties2KHR
  (:sType VkStructureType)#|MUST-BE :IMAGE-FORMAT-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:imageFormatProperties (:struct VkImageFormatProperties)))

(cffi:defcstruct VkImageSubresourceRange
  (:aspectMask VkImageAspectFlags)
  (:baseMipLevel :uint32)
  (:levelCount :uint32)
  (:baseArrayLayer :uint32)
  (:layerCount :uint32))

(cffi:defcstruct VkImageMemoryBarrier
  (:sType VkStructureType)#|MUST-BE :IMAGE-MEMORY-BARRIER|#
  (:pNext (:pointer :void))
  (:srcAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:dstAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:oldLayout VkImageLayout)
  (:newLayout VkImageLayout)
  (:srcQueueFamilyIndex :uint32)
  (:dstQueueFamilyIndex :uint32)
  (:image VkImage)#|OPAQUE T|#
  (:subresourceRange (:struct VkImageSubresourceRange)))

(cffi:defcstruct VkImageResolve
  (:srcSubresource (:struct VkImageSubresourceLayers))
  (:srcOffset (:struct VkOffset3D))
  (:dstSubresource (:struct VkImageSubresourceLayers))
  (:dstOffset (:struct VkOffset3D))
  (:extent (:struct VkExtent3D)))

(cffi:defcstruct VkImageSwapchainCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :IMAGE-SWAPCHAIN-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:swapchain VkSwapchainKHR)#|OPTIONAL (:true) OPAQUE T|#)

(cffi:defcstruct VkImageViewCreateInfo
  (:sType VkStructureType)#|MUST-BE :IMAGE-VIEW-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkImageViewCreateFlags)#|OPTIONAL (:true)|#
  (:image VkImage)#|OPAQUE T|#
  (:viewType VkImageViewType)
  (:format VkFormat)
  (:components (:struct VkComponentMapping))
  (:subresourceRange (:struct VkImageSubresourceRange)))

(cffi:defcstruct VkImportMemoryFdInfoKHX
  (:sType VkStructureType)#|MUST-BE :IMPORT-MEMORY-FD-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleType VkExternalMemoryHandleTypeFlagBitsKHX)#|OPTIONAL (:true)|#
  (:fd :int))

(cffi:defcstruct VkImportMemoryWin32HandleInfoKHX
  (:sType VkStructureType)#|MUST-BE :IMPORT-MEMORY-WIN32-HANDLE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleType VkExternalMemoryHandleTypeFlagBitsKHX)#|OPTIONAL (:true)|#
  (:handle HANDLE))

(cffi:defcstruct VkImportMemoryWin32HandleInfoNV
  (:sType VkStructureType)#|MUST-BE :IMPORT-MEMORY-WIN32-HANDLE-INFO-NV|#
  (:pNext (:pointer :void))
  (:handleType VkExternalMemoryHandleTypeFlagsNV)#|OPTIONAL (:true)|#
  (:handle HANDLE)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkImportSemaphoreFdInfoKHX
  (:sType VkStructureType)#|MUST-BE :IMPORT-SEMAPHORE-FD-INFO-KHX|#
  (:pNext (:pointer :void))
  (:semaphore VkSemaphore)#|OPAQUE T|#
  (:handleType VkExternalSemaphoreHandleTypeFlagBitsKHX)
  (:fd :int))

(cffi:defcstruct VkImportSemaphoreWin32HandleInfoKHX
  (:sType VkStructureType)#|MUST-BE :IMPORT-SEMAPHORE-WIN32-HANDLE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:semaphore VkSemaphore)#|OPAQUE T|#
  (:handleType VkExternalSemaphoreHandleTypeFlagsKHX)
  (:handle HANDLE))

(cffi:defcstruct VkIndirectCommandsLayoutTokenNVX
  (:tokenType VkIndirectCommandsTokenTypeNVX)
  (:bindingUnit :uint32)
  (:dynamicCount :uint32)
  (:divisor :uint32))

(cffi:defcstruct VkIndirectCommandsLayoutCreateInfoNVX
  (:sType VkStructureType)#|MUST-BE :INDIRECT-COMMANDS-LAYOUT-CREATE-INFO-NVX|#
  (:pNext (:pointer :void))
  (:pipelineBindPoint VkPipelineBindPoint)
  (:flags VkIndirectCommandsLayoutUsageFlagsNVX)
  (:tokenCount :uint32)
  (:pTokens (:pointer (:struct VkIndirectCommandsLayoutTokenNVX)))#|LEN (:tokenCount)|#)

(cffi:defcstruct VkInstanceCreateInfo
  (:sType VkStructureType)#|MUST-BE :INSTANCE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkInstanceCreateFlags)#|OPTIONAL (:true)|#
  (:pApplicationInfo (:pointer (:struct VkApplicationInfo)))#|OPTIONAL (:true)|#
  (:enabledLayerCount :uint32)#|OPTIONAL (:true)|#
  (:ppEnabledLayerNames (:pointer (:pointer :char)))#|LEN (:enabledLayerCount
                                                          NULL-TERMINATED)|#
  (:enabledExtensionCount :uint32)#|OPTIONAL (:true)|#
  (:ppEnabledExtensionNames (:pointer (:pointer :char)))#|LEN (:enabledExtensionCount
                                                              NULL-TERMINATED)|#)

(cffi:defcstruct VkLayerProperties
  (:layerName :char :count 256)
  (:specVersion :uint32)
  (:implementationVersion :uint32)
  (:description :char :count 256))

(cffi:defcstruct VkMacOSSurfaceCreateInfoMVK
  (:sType VkStructureType)#|MUST-BE :MACOS-SURFACE-CREATE-INFO-MVK|#
  (:pNext (:pointer :void))
  (:flags VkMacOSSurfaceCreateFlagsMVK)#|OPTIONAL (:true)|#
  (:pView (:pointer :void)))

(cffi:defcstruct VkMappedMemoryRange
  (:sType VkStructureType)#|MUST-BE :MAPPED-MEMORY-RANGE|#
  (:pNext (:pointer :void))
  (:memory VkDeviceMemory)#|OPAQUE T|#
  (:offset VkDeviceSize)
  (:size VkDeviceSize))

(cffi:defcstruct VkMemoryAllocateFlagsInfoKHX
  (:sType VkStructureType)#|MUST-BE :MEMORY-ALLOCATE-FLAGS-INFO-KHX|#
  (:pNext (:pointer :void))
  (:flags VkMemoryAllocateFlagsKHX)#|OPTIONAL (:true)|#
  (:deviceMask :uint32))

(cffi:defcstruct VkMemoryAllocateInfo
  (:sType VkStructureType)#|MUST-BE :MEMORY-ALLOCATE-INFO|#
  (:pNext (:pointer :void))
  (:allocationSize VkDeviceSize)
  (:memoryTypeIndex :uint32))

(cffi:defcstruct VkMemoryBarrier
  (:sType VkStructureType)#|MUST-BE :MEMORY-BARRIER|#
  (:pNext (:pointer :void))
  (:srcAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:dstAccessMask VkAccessFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkMemoryFdPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :MEMORY-FD-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:memoryTypeBits :uint32))

(cffi:defcstruct VkMemoryHeap
  (:size VkDeviceSize)
  (:flags VkMemoryHeapFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkMemoryRequirements
  (:size VkDeviceSize)
  (:alignment VkDeviceSize)
  (:memoryTypeBits :uint32))

(cffi:defcstruct VkMemoryType
  (:propertyFlags VkMemoryPropertyFlags)#|OPTIONAL (:true)|#
  (:heapIndex :uint32))

(cffi:defcstruct VkMemoryWin32HandlePropertiesKHX
  (:sType VkStructureType)#|MUST-BE :MEMORY-WIN32-HANDLE-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:memoryTypeBits :uint32))

(cffi:defcstruct VkMirSurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :MIR-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkMirSurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:connection (:pointer MirConnection))#|OPAQUE T|#
  (:mirSurface (:pointer MirSurface))#|OPAQUE T|#)

(cffi:defcstruct VkObjectTableCreateInfoNVX
  (:sType VkStructureType)#|MUST-BE :OBJECT-TABLE-CREATE-INFO-NVX|#
  (:pNext (:pointer :void))
  (:objectCount :uint32)
  (:pObjectEntryTypes (:pointer VkObjectEntryTypeNVX))#|LEN (:objectCount)|#
  (:pObjectEntryCounts (:pointer :uint32))#|LEN (:objectCount)|#
  (:pObjectEntryUsageFlags (:pointer VkObjectEntryUsageFlagsNVX))#|LEN (:objectCount)|#
  (:maxUniformBuffersPerDescriptor :uint32)
  (:maxStorageBuffersPerDescriptor :uint32)
  (:maxStorageImagesPerDescriptor :uint32)
  (:maxSampledImagesPerDescriptor :uint32)
  (:maxPipelineLayouts :uint32))

(cffi:defcstruct VkObjectTableDescriptorSetEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX)
  (:pipelineLayout VkPipelineLayout)#|OPAQUE T|#
  (:descriptorSet VkDescriptorSet)#|OPAQUE T|#)

(cffi:defcstruct VkObjectTableEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX))

(cffi:defcstruct VkObjectTableIndexBufferEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX)
  (:buffer VkBuffer)#|OPAQUE T|#
  (:indexType VkIndexType))

(cffi:defcstruct VkObjectTablePipelineEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX)
  (:pipeline VkPipeline)#|OPAQUE T|#)

(cffi:defcstruct VkObjectTablePushConstantEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX)
  (:pipelineLayout VkPipelineLayout)#|OPAQUE T|#
  (:stageFlags VkShaderStageFlags))

(cffi:defcstruct VkObjectTableVertexBufferEntryNVX
  (:type VkObjectEntryTypeNVX)
  (:flags VkObjectEntryUsageFlagsNVX)
  (:buffer VkBuffer)#|OPAQUE T|#)

(cffi:defcstruct VkPastPresentationTimingGOOGLE
  (:presentID :uint32)
  (:desiredPresentTime :uint64)
  (:actualPresentTime :uint64)
  (:earliestPresentTime :uint64)
  (:presentMargin :uint64))

(cffi:defcstruct VkPhysicalDeviceDiscardRectanglePropertiesEXT
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-DISCARD-RECTANGLE-PROPERTIES-EXT|#
  (:pNext (:pointer :void))
  (:maxDiscardRectangles :uint32))

(cffi:defcstruct VkPhysicalDeviceExternalBufferInfoKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-EXTERNAL-BUFFER-INFO-KHX|#
  (:pNext (:pointer :void))
  (:flags VkBufferCreateFlags)#|OPTIONAL (:true)|#
  (:usage VkBufferUsageFlags)
  (:handleType VkExternalMemoryHandleTypeFlagBitsKHX))

(cffi:defcstruct VkPhysicalDeviceExternalImageFormatInfoKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-EXTERNAL-IMAGE-FORMAT-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleType VkExternalMemoryHandleTypeFlagBitsKHX)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkPhysicalDeviceExternalSemaphoreInfoKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-EXTERNAL-SEMAPHORE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:handleType VkExternalSemaphoreHandleTypeFlagBitsKHX))

(cffi:defcstruct VkPhysicalDeviceFeatures2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-FEATURES-2-KHR|#
  (:pNext (:pointer :void))
  (:features (:struct VkPhysicalDeviceFeatures)))

(cffi:defcstruct VkPhysicalDeviceGroupPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-GROUP-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:physicalDeviceCount :uint32)
  (:physicalDevices VkPhysicalDevice :count 32)#|OPAQUE T|#
  (:subsetAllocation VkBool32))

(cffi:defcstruct VkPhysicalDeviceIDPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-ID-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:deviceUUID :uint8 :count 16)
  (:driverUUID :uint8 :count 16)
  (:deviceLUID :uint8 :count 8)
  (:deviceLUIDValid VkBool32))

(cffi:defcstruct VkPhysicalDeviceImageFormatInfo2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-IMAGE-FORMAT-INFO-2-KHR|#
  (:pNext (:pointer :void))
  (:format VkFormat)
  (:type VkImageType)
  (:tiling VkImageTiling)
  (:usage VkImageUsageFlags)
  (:flags VkImageCreateFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkPhysicalDeviceLimits
  (:maxImageDimension1D :uint32)
  (:maxImageDimension2D :uint32)
  (:maxImageDimension3D :uint32)
  (:maxImageDimensionCube :uint32)
  (:maxImageArrayLayers :uint32)
  (:maxTexelBufferElements :uint32)
  (:maxUniformBufferRange :uint32)
  (:maxStorageBufferRange :uint32)
  (:maxPushConstantsSize :uint32)
  (:maxMemoryAllocationCount :uint32)
  (:maxSamplerAllocationCount :uint32)
  (:bufferImageGranularity VkDeviceSize)
  (:sparseAddressSpaceSize VkDeviceSize)
  (:maxBoundDescriptorSets :uint32)
  (:maxPerStageDescriptorSamplers :uint32)
  (:maxPerStageDescriptorUniformBuffers :uint32)
  (:maxPerStageDescriptorStorageBuffers :uint32)
  (:maxPerStageDescriptorSampledImages :uint32)
  (:maxPerStageDescriptorStorageImages :uint32)
  (:maxPerStageDescriptorInputAttachments :uint32)
  (:maxPerStageResources :uint32)
  (:maxDescriptorSetSamplers :uint32)
  (:maxDescriptorSetUniformBuffers :uint32)
  (:maxDescriptorSetUniformBuffersDynamic :uint32)
  (:maxDescriptorSetStorageBuffers :uint32)
  (:maxDescriptorSetStorageBuffersDynamic :uint32)
  (:maxDescriptorSetSampledImages :uint32)
  (:maxDescriptorSetStorageImages :uint32)
  (:maxDescriptorSetInputAttachments :uint32)
  (:maxVertexInputAttributes :uint32)
  (:maxVertexInputBindings :uint32)
  (:maxVertexInputAttributeOffset :uint32)
  (:maxVertexInputBindingStride :uint32)
  (:maxVertexOutputComponents :uint32)
  (:maxTessellationGenerationLevel :uint32)
  (:maxTessellationPatchSize :uint32)
  (:maxTessellationControlPerVertexInputComponents :uint32)
  (:maxTessellationControlPerVertexOutputComponents :uint32)
  (:maxTessellationControlPerPatchOutputComponents :uint32)
  (:maxTessellationControlTotalOutputComponents :uint32)
  (:maxTessellationEvaluationInputComponents :uint32)
  (:maxTessellationEvaluationOutputComponents :uint32)
  (:maxGeometryShaderInvocations :uint32)
  (:maxGeometryInputComponents :uint32)
  (:maxGeometryOutputComponents :uint32)
  (:maxGeometryOutputVertices :uint32)
  (:maxGeometryTotalOutputComponents :uint32)
  (:maxFragmentInputComponents :uint32)
  (:maxFragmentOutputAttachments :uint32)
  (:maxFragmentDualSrcAttachments :uint32)
  (:maxFragmentCombinedOutputResources :uint32)
  (:maxComputeSharedMemorySize :uint32)
  (:maxComputeWorkGroupCount :uint32 :count 3)
  (:maxComputeWorkGroupInvocations :uint32)
  (:maxComputeWorkGroupSize :uint32 :count 3)
  (:subPixelPrecisionBits :uint32)
  (:subTexelPrecisionBits :uint32)
  (:mipmapPrecisionBits :uint32)
  (:maxDrawIndexedIndexValue :uint32)
  (:maxDrawIndirectCount :uint32)
  (:maxSamplerLodBias :float)
  (:maxSamplerAnisotropy :float)
  (:maxViewports :uint32)
  (:maxViewportDimensions :uint32 :count 2)
  (:viewportBoundsRange :float :count 2)
  (:viewportSubPixelBits :uint32)
  (:minMemoryMapAlignment size-t)
  (:minTexelBufferOffsetAlignment VkDeviceSize)
  (:minUniformBufferOffsetAlignment VkDeviceSize)
  (:minStorageBufferOffsetAlignment VkDeviceSize)
  (:minTexelOffset :int32)
  (:maxTexelOffset :uint32)
  (:minTexelGatherOffset :int32)
  (:maxTexelGatherOffset :uint32)
  (:minInterpolationOffset :float)
  (:maxInterpolationOffset :float)
  (:subPixelInterpolationOffsetBits :uint32)
  (:maxFramebufferWidth :uint32)
  (:maxFramebufferHeight :uint32)
  (:maxFramebufferLayers :uint32)
  (:framebufferColorSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:framebufferDepthSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:framebufferStencilSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:framebufferNoAttachmentsSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:maxColorAttachments :uint32)
  (:sampledImageColorSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:sampledImageIntegerSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:sampledImageDepthSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:sampledImageStencilSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:storageImageSampleCounts VkSampleCountFlags)#|OPTIONAL (:true)|#
  (:maxSampleMaskWords :uint32)
  (:timestampComputeAndGraphics VkBool32)
  (:timestampPeriod :float)
  (:maxClipDistances :uint32)
  (:maxCullDistances :uint32)
  (:maxCombinedClipAndCullDistances :uint32)
  (:discreteQueuePriorities :uint32)
  (:pointSizeRange :float :count 2)
  (:lineWidthRange :float :count 2)
  (:pointSizeGranularity :float)
  (:lineWidthGranularity :float)
  (:strictLines VkBool32)
  (:standardSampleLocations VkBool32)
  (:optimalBufferCopyOffsetAlignment VkDeviceSize)
  (:optimalBufferCopyRowPitchAlignment VkDeviceSize)
  (:nonCoherentAtomSize VkDeviceSize))

(cffi:defcstruct VkPhysicalDeviceMemoryProperties
  (:memoryTypeCount :uint32)
  (:memoryTypes (:struct VkMemoryType) :count 32)
  (:memoryHeapCount :uint32)
  (:memoryHeaps (:struct VkMemoryHeap) :count 16))

(cffi:defcstruct VkPhysicalDeviceMemoryProperties2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-MEMORY-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:memoryProperties (:struct VkPhysicalDeviceMemoryProperties)))

(cffi:defcstruct VkPhysicalDeviceMultiviewFeaturesKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-MULTIVIEW-FEATURES-KHX|#
  (:pNext (:pointer :void))
  (:multiview VkBool32)
  (:multiviewGeometryShader VkBool32)
  (:multiviewTessellationShader VkBool32))

(cffi:defcstruct VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-MULTIVIEW-PER-VIEW-ATTRIBUTES-PROPERTIES-NVX|#
  (:pNext (:pointer :void))
  (:perViewPositionAllComponents VkBool32))

(cffi:defcstruct VkPhysicalDeviceMultiviewPropertiesKHX
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-MULTIVIEW-PROPERTIES-KHX|#
  (:pNext (:pointer :void))
  (:maxMultiviewViewCount :uint32)
  (:maxMultiviewInstanceIndex :uint32))

(cffi:defcstruct VkPhysicalDeviceSparseProperties
  (:residencyStandard2DBlockShape VkBool32)
  (:residencyStandard2DMultisampleBlockShape VkBool32)
  (:residencyStandard3DBlockShape VkBool32)
  (:residencyAlignedMipSize VkBool32)
  (:residencyNonResidentStrict VkBool32))

(cffi:defcstruct VkPhysicalDeviceProperties
  (:apiVersion :uint32)
  (:driverVersion :uint32)
  (:vendorID :uint32)
  (:deviceID :uint32)
  (:deviceType VkPhysicalDeviceType)
  (:deviceName :char :count 256)
  (:pipelineCacheUUID :uint8 :count 16)
  (:limits (:struct VkPhysicalDeviceLimits))
  (:sparseProperties (:struct VkPhysicalDeviceSparseProperties)))

(cffi:defcstruct VkPhysicalDeviceProperties2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:properties (:struct VkPhysicalDeviceProperties)))

(cffi:defcstruct VkPhysicalDevicePushDescriptorPropertiesKHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-PUSH-DESCRIPTOR-PROPERTIES-KHR|#
  (:pNext (:pointer :void))
  (:maxPushDescriptors :uint32))

(cffi:defcstruct VkPhysicalDeviceSparseImageFormatInfo2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-SPARSE-IMAGE-FORMAT-INFO-2-KHR|#
  (:pNext (:pointer :void))
  (:format VkFormat)
  (:type VkImageType)
  (:samples VkSampleCountFlagBits)
  (:usage VkImageUsageFlags)
  (:tiling VkImageTiling))

(cffi:defcstruct VkPhysicalDeviceSurfaceInfo2KHR
  (:sType VkStructureType)#|MUST-BE :PHYSICAL-DEVICE-SURFACE-INFO-2-KHR|#
  (:pNext (:pointer :void))
  (:surface VkSurfaceKHR)#|OPAQUE T|#)

(cffi:defcstruct VkPipelineCacheCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-CACHE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineCacheCreateFlags)#|OPTIONAL (:true)|#
  (:initialDataSize size-t)#|OPTIONAL (:true)|#
  (:pInitialData (:pointer :void))#|LEN (:initialDataSize)|#)

(cffi:defcstruct VkPipelineDiscardRectangleStateCreateInfoEXT
  (:sType VkStructureType)#|MUST-BE :PIPELINE-DISCARD-RECTANGLE-STATE-CREATE-INFO-EXT|#
  (:pNext (:pointer :void))
  (:flags VkPipelineDiscardRectangleStateCreateFlagsEXT)#|OPTIONAL (:true)|#
  (:discardRectangleMode VkDiscardRectangleModeEXT)
  (:discardRectangleCount :uint32)#|OPTIONAL (:true)|#
  (:pDiscardRectangles (:pointer (:struct VkRect2D)))#|OPTIONAL (:true) LEN (:discardRectangleCount)|#)

(cffi:defcstruct VkPushConstantRange
  (:stageFlags VkShaderStageFlags)
  (:offset :uint32)
  (:size :uint32))

(cffi:defcstruct VkPipelineLayoutCreateInfo
  (:sType VkStructureType)#|MUST-BE :PIPELINE-LAYOUT-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkPipelineLayoutCreateFlags)#|OPTIONAL (:true)|#
  (:setLayoutCount :uint32)#|OPTIONAL (:true)|#
  (:pSetLayouts (:pointer VkDescriptorSetLayout))#|LEN (:setLayoutCount) OPAQUE T|#
  (:pushConstantRangeCount :uint32)#|OPTIONAL (:true)|#
  (:pPushConstantRanges (:pointer (:struct VkPushConstantRange)))#|LEN (:pushConstantRangeCount)|#)

(cffi:defcstruct VkPipelineRasterizationStateRasterizationOrderAMD
  (:sType VkStructureType)#|MUST-BE :PIPELINE-RASTERIZATION-STATE-RASTERIZATION-ORDER-AMD|#
  (:pNext (:pointer :void))
  (:rasterizationOrder VkRasterizationOrderAMD))

(cffi:defcstruct VkViewportSwizzleNV
  (:x VkViewportCoordinateSwizzleNV)
  (:y VkViewportCoordinateSwizzleNV)
  (:z VkViewportCoordinateSwizzleNV)
  (:w VkViewportCoordinateSwizzleNV))

(cffi:defcstruct VkPipelineViewportSwizzleStateCreateInfoNV
  (:sType VkStructureType)#|MUST-BE :PIPELINE-VIEWPORT-SWIZZLE-STATE-CREATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:flags VkPipelineViewportSwizzleStateCreateFlagsNV)#|OPTIONAL (:true)|#
  (:viewportCount :uint32)
  (:pViewportSwizzles (:pointer (:struct VkViewportSwizzleNV)))#|OPTIONAL (:true) LEN (:viewportCount)|#)

(cffi:defcstruct VkViewportWScalingNV
  (:xcoeff :float)
  (:ycoeff :float))

(cffi:defcstruct VkPipelineViewportWScalingStateCreateInfoNV
  (:sType VkStructureType)#|MUST-BE :PIPELINE-VIEWPORT-W-SCALING-STATE-CREATE-INFO-NV|#
  (:pNext (:pointer :void))
  (:viewportWScalingEnable VkBool32)
  (:viewportCount :uint32)
  (:pViewportWScalings (:pointer (:struct VkViewportWScalingNV)))#|LEN (:viewportCount)|#)

(cffi:defcstruct VkPresentInfoKHR
  (:sType VkStructureType)#|MUST-BE :PRESENT-INFO-KHR|#
  (:pNext (:pointer :void))
  (:waitSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pWaitSemaphores (:pointer VkSemaphore))#|OPTIONAL (:true) LEN (:waitSemaphoreCount) OPAQUE T|#
  (:swapchainCount :uint32)
  (:pSwapchains (:pointer VkSwapchainKHR))#|LEN (:swapchainCount) OPAQUE T|#
  (:pImageIndices (:pointer :uint32))#|LEN (:swapchainCount)|#
  (:pResults (:pointer VkResult))#|OPTIONAL (:true) LEN (:swapchainCount)|#)

(cffi:defcstruct VkRectLayerKHR
  (:offset (:struct VkOffset2D))
  (:extent (:struct VkExtent2D))
  (:layer :uint32))

(cffi:defcstruct VkPresentRegionKHR
  (:rectangleCount :uint32)#|OPTIONAL (:true)|#
  (:pRectangles (:pointer (:struct VkRectLayerKHR)))#|OPTIONAL (:true) LEN (:rectangleCount)|#)

(cffi:defcstruct VkPresentRegionsKHR
  (:sType VkStructureType)#|MUST-BE :PRESENT-REGIONS-KHR|#
  (:pNext (:pointer :void))
  (:swapchainCount :uint32)
  (:pRegions (:pointer (:struct VkPresentRegionKHR)))#|OPTIONAL (:true) LEN (:swapchainCount)|#)

(cffi:defcstruct VkPresentTimeGOOGLE
  (:presentID :uint32)
  (:desiredPresentTime :uint64))

(cffi:defcstruct VkPresentTimesInfoGOOGLE
  (:sType VkStructureType)#|MUST-BE :PRESENT-TIMES-INFO-GOOGLE|#
  (:pNext (:pointer :void))
  (:swapchainCount :uint32)
  (:pTimes (:pointer (:struct VkPresentTimeGOOGLE)))#|OPTIONAL (:true) LEN (:swapchainCount)|#)

(cffi:defcstruct VkQueryPoolCreateInfo
  (:sType VkStructureType)#|MUST-BE :QUERY-POOL-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkQueryPoolCreateFlags)#|OPTIONAL (:true)|#
  (:queryType VkQueryType)
  (:queryCount :uint32)
  (:pipelineStatistics VkQueryPipelineStatisticFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkQueueFamilyProperties
  (:queueFlags VkQueueFlags)#|OPTIONAL (:true)|#
  (:queueCount :uint32)
  (:timestampValidBits :uint32)
  (:minImageTransferGranularity (:struct VkExtent3D)))

(cffi:defcstruct VkQueueFamilyProperties2KHR
  (:sType VkStructureType)#|MUST-BE :QUEUE-FAMILY-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:queueFamilyProperties (:struct VkQueueFamilyProperties)))

(cffi:defcstruct VkRect3D
  (:offset (:struct VkOffset3D))
  (:extent (:struct VkExtent3D)))

(cffi:defcstruct VkRefreshCycleDurationGOOGLE
  (:refreshDuration :uint64))

(cffi:defcstruct VkRenderPassBeginInfo
  (:sType VkStructureType)#|MUST-BE :RENDER-PASS-BEGIN-INFO|#
  (:pNext (:pointer :void))
  (:renderPass VkRenderPass)#|OPAQUE T|#
  (:framebuffer VkFramebuffer)#|OPAQUE T|#
  (:renderArea (:struct VkRect2D))
  (:clearValueCount :uint32)#|OPTIONAL (:true)|#
  (:pClearValues (:pointer (:union VkClearValue)))#|LEN (:clearValueCount)|#)

(cffi:defcstruct VkSubpassDescription
  (:flags VkSubpassDescriptionFlags)#|OPTIONAL (:true)|#
  (:pipelineBindPoint VkPipelineBindPoint)
  (:inputAttachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pInputAttachments (:pointer (:struct VkAttachmentReference)))#|LEN (:inputAttachmentCount)|#
  (:colorAttachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pColorAttachments (:pointer (:struct VkAttachmentReference)))#|LEN (:colorAttachmentCount)|#
  (:pResolveAttachments (:pointer (:struct VkAttachmentReference)))#|OPTIONAL (:true) LEN (:colorAttachmentCount)|#
  (:pDepthStencilAttachment (:pointer (:struct VkAttachmentReference)))#|OPTIONAL (:true)|#
  (:preserveAttachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pPreserveAttachments (:pointer :uint32))#|LEN (:preserveAttachmentCount)|#)

(cffi:defcstruct VkSubpassDependency
  (:srcSubpass :uint32)
  (:dstSubpass :uint32)
  (:srcStageMask VkPipelineStageFlags)
  (:dstStageMask VkPipelineStageFlags)
  (:srcAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:dstAccessMask VkAccessFlags)#|OPTIONAL (:true)|#
  (:dependencyFlags VkDependencyFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkRenderPassCreateInfo
  (:sType VkStructureType)#|MUST-BE :RENDER-PASS-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkRenderPassCreateFlags)#|OPTIONAL (:true)|#
  (:attachmentCount :uint32)#|OPTIONAL (:true)|#
  (:pAttachments (:pointer (:struct VkAttachmentDescription)))#|LEN (:attachmentCount)|#
  (:subpassCount :uint32)
  (:pSubpasses (:pointer (:struct VkSubpassDescription)))#|LEN (:subpassCount)|#
  (:dependencyCount :uint32)#|OPTIONAL (:true)|#
  (:pDependencies (:pointer (:struct VkSubpassDependency)))#|LEN (:dependencyCount)|#)

(cffi:defcstruct VkRenderPassMultiviewCreateInfoKHX
  (:sType VkStructureType)#|MUST-BE :RENDER-PASS-MULTIVIEW-CREATE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:subpassCount :uint32)#|OPTIONAL (:true)|#
  (:pViewMasks (:pointer :uint32))#|LEN (:subpassCount)|#
  (:dependencyCount :uint32)#|OPTIONAL (:true)|#
  (:pViewOffsets (:pointer :int32))#|LEN (:dependencyCount)|#
  (:correlationMaskCount :uint32)#|OPTIONAL (:true)|#
  (:pCorrelationMasks (:pointer :uint32))#|LEN (:correlationMaskCount)|#)

(cffi:defcstruct VkSamplerCreateInfo
  (:sType VkStructureType)#|MUST-BE :SAMPLER-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkSamplerCreateFlags)#|OPTIONAL (:true)|#
  (:magFilter VkFilter)
  (:minFilter VkFilter)
  (:mipmapMode VkSamplerMipmapMode)
  (:addressModeU VkSamplerAddressMode)
  (:addressModeV VkSamplerAddressMode)
  (:addressModeW VkSamplerAddressMode)
  (:mipLodBias :float)
  (:anisotropyEnable VkBool32)
  (:maxAnisotropy :float)
  (:compareEnable VkBool32)
  (:compareOp VkCompareOp)
  (:minLod :float)
  (:maxLod :float)
  (:borderColor VkBorderColor)
  (:unnormalizedCoordinates VkBool32))

(cffi:defcstruct VkSemaphoreCreateInfo
  (:sType VkStructureType)#|MUST-BE :SEMAPHORE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkSemaphoreCreateFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkShaderModuleCreateInfo
  (:sType VkStructureType)#|MUST-BE :SHADER-MODULE-CREATE-INFO|#
  (:pNext (:pointer :void))
  (:flags VkShaderModuleCreateFlags)#|OPTIONAL (:true)|#
  (:codeSize size-t)
  (:pCode (:pointer :uint32))#|LEN (latexmath:[codeSize \over 4])|#)

(cffi:defcstruct VkSharedPresentSurfaceCapabilitiesKHR
  (:sType VkStructureType)#|MUST-BE :SHARED-PRESENT-SURFACE-CAPABILITIES-KHR|#
  (:pNext (:pointer :void))
  (:sharedPresentSupportedUsageFlags VkImageUsageFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSparseImageFormatProperties
  (:aspectMask VkImageAspectFlags)#|OPTIONAL (:true)|#
  (:imageGranularity (:struct VkExtent3D))
  (:flags VkSparseImageFormatFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSparseImageFormatProperties2KHR
  (:sType VkStructureType)#|MUST-BE :SPARSE-IMAGE-FORMAT-PROPERTIES-2-KHR|#
  (:pNext (:pointer :void))
  (:properties (:struct VkSparseImageFormatProperties)))

(cffi:defcstruct VkSparseImageMemoryRequirements
  (:formatProperties (:struct VkSparseImageFormatProperties))
  (:imageMipTailFirstLod :uint32)
  (:imageMipTailSize VkDeviceSize)
  (:imageMipTailOffset VkDeviceSize)
  (:imageMipTailStride VkDeviceSize))

(cffi:defcstruct VkSubmitInfo
  (:sType VkStructureType)#|MUST-BE :SUBMIT-INFO|#
  (:pNext (:pointer :void))
  (:waitSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pWaitSemaphores (:pointer VkSemaphore))#|LEN (:waitSemaphoreCount) OPAQUE T|#
  (:pWaitDstStageMask (:pointer VkPipelineStageFlags))#|LEN (:waitSemaphoreCount)|#
  (:commandBufferCount :uint32)#|OPTIONAL (:true)|#
  (:pCommandBuffers (:pointer VkCommandBuffer))#|LEN (:commandBufferCount) OPAQUE T|#
  (:signalSemaphoreCount :uint32)#|OPTIONAL (:true)|#
  (:pSignalSemaphores (:pointer VkSemaphore))#|LEN (:signalSemaphoreCount) OPAQUE T|#)

(cffi:defcstruct VkSubresourceLayout
  (:offset VkDeviceSize)
  (:size VkDeviceSize)
  (:rowPitch VkDeviceSize)
  (:arrayPitch VkDeviceSize)
  (:depthPitch VkDeviceSize))

(cffi:defcstruct VkSurfaceCapabilities2EXT
  (:sType VkStructureType)#|MUST-BE :SURFACE-CAPABILITIES2-EXT|#
  (:pNext (:pointer :void))
  (:minImageCount :uint32)
  (:maxImageCount :uint32)
  (:currentExtent (:struct VkExtent2D))
  (:minImageExtent (:struct VkExtent2D))
  (:maxImageExtent (:struct VkExtent2D))
  (:maxImageArrayLayers :uint32)
  (:supportedTransforms VkSurfaceTransformFlagsKHR)#|OPTIONAL (:true)|#
  (:currentTransform VkSurfaceTransformFlagBitsKHR)
  (:supportedCompositeAlpha VkCompositeAlphaFlagsKHR)#|OPTIONAL (:true)|#
  (:supportedUsageFlags VkImageUsageFlags)#|OPTIONAL (:true)|#
  (:supportedSurfaceCounters VkSurfaceCounterFlagsEXT)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSurfaceCapabilitiesKHR
  (:minImageCount :uint32)
  (:maxImageCount :uint32)
  (:currentExtent (:struct VkExtent2D))
  (:minImageExtent (:struct VkExtent2D))
  (:maxImageExtent (:struct VkExtent2D))
  (:maxImageArrayLayers :uint32)
  (:supportedTransforms VkSurfaceTransformFlagsKHR)#|OPTIONAL (:true)|#
  (:currentTransform VkSurfaceTransformFlagBitsKHR)
  (:supportedCompositeAlpha VkCompositeAlphaFlagsKHR)#|OPTIONAL (:true)|#
  (:supportedUsageFlags VkImageUsageFlags)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSurfaceCapabilities2KHR
  (:sType VkStructureType)#|MUST-BE :SURFACE-CAPABILITIES-2-KHR|#
  (:pNext (:pointer :void))
  (:surfaceCapabilities (:struct VkSurfaceCapabilitiesKHR)))

(cffi:defcstruct VkSurfaceFormatKHR
  (:format VkFormat)
  (:colorSpace VkColorSpaceKHR))

(cffi:defcstruct VkSurfaceFormat2KHR
  (:sType VkStructureType)#|MUST-BE :SURFACE-FORMAT-2-KHR|#
  (:pNext (:pointer :void))
  (:surfaceFormat (:struct VkSurfaceFormatKHR)))

(cffi:defcstruct VkSwapchainCounterCreateInfoEXT
  (:sType VkStructureType)#|MUST-BE :SWAPCHAIN-COUNTER-CREATE-INFO-EXT|#
  (:pNext (:pointer :void))
  (:surfaceCounters VkSurfaceCounterFlagsEXT)#|OPTIONAL (:true)|#)

(cffi:defcstruct VkSwapchainCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :SWAPCHAIN-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkSwapchainCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:surface VkSurfaceKHR)#|OPAQUE T|#
  (:minImageCount :uint32)
  (:imageFormat VkFormat)
  (:imageColorSpace VkColorSpaceKHR)
  (:imageExtent (:struct VkExtent2D))
  (:imageArrayLayers :uint32)
  (:imageUsage VkImageUsageFlags)
  (:imageSharingMode VkSharingMode)
  (:queueFamilyIndexCount :uint32)#|OPTIONAL (:true)|#
  (:pQueueFamilyIndices (:pointer :uint32))#|LEN (:queueFamilyIndexCount)|#
  (:preTransform VkSurfaceTransformFlagBitsKHR)
  (:compositeAlpha VkCompositeAlphaFlagBitsKHR)
  (:presentMode VkPresentModeKHR)
  (:clipped VkBool32)
  (:oldSwapchain VkSwapchainKHR)#|OPTIONAL (:true) OPAQUE T|#)

(cffi:defcstruct VkTextureLODGatherFormatPropertiesAMD
  (:sType VkStructureType)#|MUST-BE :TEXTURE-LOD-GATHER-FORMAT-PROPERTIES-AMD|#
  (:pNext (:pointer :void))
  (:supportsTextureGatherLODBiasAMD VkBool32))

(cffi:defcstruct VkValidationFlagsEXT
  (:sType VkStructureType)#|MUST-BE :VALIDATION-FLAGS-EXT|#
  (:pNext (:pointer :void))
  (:disabledValidationCheckCount :uint32)
  (:pDisabledValidationChecks (:pointer VkValidationCheckEXT))#|LEN (:disabledValidationCheckCount)|#)

(cffi:defcstruct VkViSurfaceCreateInfoNN
  (:sType VkStructureType)#|MUST-BE :VI-SURFACE-CREATE-INFO-NN|#
  (:pNext (:pointer :void))
  (:flags VkViSurfaceCreateFlagsNN)#|OPTIONAL (:true)|#
  (:window (:pointer :void)))

(cffi:defcstruct VkWaylandSurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :WAYLAND-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkWaylandSurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:display (:pointer (:struct wl_display)))#|OPAQUE T|#
  (:surface (:pointer (:struct wl_surface)))#|OPAQUE T|#)

(cffi:defcstruct VkWin32KeyedMutexAcquireReleaseInfoKHX
  (:sType VkStructureType)#|MUST-BE :WIN32-KEYED-MUTEX-ACQUIRE-RELEASE-INFO-KHX|#
  (:pNext (:pointer :void))
  (:acquireCount :uint32)#|OPTIONAL (:true)|#
  (:pAcquireSyncs (:pointer VkDeviceMemory))#|LEN (:acquireCount) OPAQUE T|#
  (:pAcquireKeys (:pointer :uint64))#|LEN (:acquireCount)|#
  (:pAcquireTimeouts (:pointer :uint32))#|LEN (:acquireCount)|#
  (:releaseCount :uint32)#|OPTIONAL (:true)|#
  (:pReleaseSyncs (:pointer VkDeviceMemory))#|LEN (:releaseCount) OPAQUE T|#
  (:pReleaseKeys (:pointer :uint64))#|LEN (:releaseCount)|#)

(cffi:defcstruct VkWin32KeyedMutexAcquireReleaseInfoNV
  (:sType VkStructureType)#|MUST-BE :WIN32-KEYED-MUTEX-ACQUIRE-RELEASE-INFO-NV|#
  (:pNext (:pointer :void))
  (:acquireCount :uint32)#|OPTIONAL (:true)|#
  (:pAcquireSyncs (:pointer VkDeviceMemory))#|LEN (:acquireCount) OPAQUE T|#
  (:pAcquireKeys (:pointer :uint64))#|LEN (:acquireCount)|#
  (:pAcquireTimeoutMilliseconds (:pointer :uint32))#|LEN (:acquireCount)|#
  (:releaseCount :uint32)#|OPTIONAL (:true)|#
  (:pReleaseSyncs (:pointer VkDeviceMemory))#|LEN (:releaseCount) OPAQUE T|#
  (:pReleaseKeys (:pointer :uint64))#|LEN (:releaseCount)|#)

(cffi:defcstruct VkWin32SurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :WIN32-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkWin32SurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:hinstance HINSTANCE)
  (:hwnd HWND))

(cffi:defcstruct VkWriteDescriptorSet
  (:sType VkStructureType)#|MUST-BE :WRITE-DESCRIPTOR-SET|#
  (:pNext (:pointer :void))
  (:dstSet VkDescriptorSet)#|OPAQUE T|#
  (:dstBinding :uint32)
  (:dstArrayElement :uint32)
  (:descriptorCount :uint32)
  (:descriptorType VkDescriptorType)
  (:pImageInfo (:pointer (:struct VkDescriptorImageInfo)))#|LEN (:descriptorCount)|#
  (:pBufferInfo (:pointer (:struct VkDescriptorBufferInfo)))#|LEN (:descriptorCount)|#
  (:pTexelBufferView (:pointer VkBufferView))#|LEN (:descriptorCount) OPAQUE T|#)

(cffi:defcstruct VkXcbSurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :XCB-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkXcbSurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:connection (:pointer xcb_connection_t))#|OPAQUE T|#
  (:window xcb_window_t))

(cffi:defcstruct VkXlibSurfaceCreateInfoKHR
  (:sType VkStructureType)#|MUST-BE :XLIB-SURFACE-CREATE-INFO-KHR|#
  (:pNext (:pointer :void))
  (:flags VkXlibSurfaceCreateFlagsKHR)#|OPTIONAL (:true)|#
  (:dpy (:pointer Display))#|OPAQUE T|#
  (:window Window))

